select 'TIJ:BE:' || t.lotid || ':' || t.area || ':' || t.module || ':' || t.parameter_name || ':' || t.ch_id || ':' || t.sample_id || ':' || t.ckc_id as PKey,
    Decode(t.parameter_name, '-', null, t.parameter_name) ParameterName, 
    Decode(t.parameter_unit, '-', null, t.parameter_unit) ParameterUnit, 
    t.sample_date SampleDate, 
    t.sample_date_utc SampleDateUtc, 
    t.ext_sample_size SampleSize,
    cast(t.ext_sigma as varchar(30)) Sigma,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_mv as varchar(20)) Mean, 
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper) as FLOAT(49)) SpecHigh,

    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_Utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    t.rv_store_flag RvStoreFlag,

    Decode(t.lotid , '-', null, t.lotid) Lot,
    Decode(t.package , '-', null, t.package) Package,
    Decode(t.familiypackage , '-', null, t.familiypackage) PackageFamily,
    Decode(t.partnumber, '-', null, t.partnumber) PartNumber,
    Decode(t.wiresize , '-', null, t.wiresize) WireSize,
    Decode(t.area, '-', null, t.area) Area,
    Decode(t.equipment , '-', null, t.equipment) ProcessEquipment,
    Decode(t.diesize , '-', null, t.diesize) DieSize,
    Decode(t.moldcompound, '-', null, t.moldcompound) MoldCompound,
    Decode(t.category , '-', null, t.category) Category,
    Decode(t.soldertype,  '-', null, t.soldertype) SolderType,
    Decode(t.wafterthickness , '-', null, t.wafterthickness) WaferThickness,
    Decode(t.leadformcategory, '-', null, t.leadformcategory) LeadFormCategory,
    Decode(t.layout,  '-', null, t.layout) Layout,
    Decode(t.track , '-', null, t.track) Track,
    Decode(t.grade , '-', null, t.grade) Grade,
    Decode(t.tool , '-', null, t.tool) MeasurementEquipment,
    Decode(t.operator , '-', null, t.operator) Operator,
    Decode(t.classification , '-', null, t.classification) Classification,
    Decode(t.hexsize,  '-', null, t.hexsize) HexSize,
    Decode(t.productionversion,  '-', null, t.productionversion) ProductionVersion,
    Decode(t.parameter_class , '-', null, t.parameter_class) ParameterClass,
    Decode(t.target_cpk , '-', null, t.target_cpk) TargetCpk,
    Decode(t.segment , '-', null, t.segment) Segment,
    Decode(t.module , '-', null, t.module) Module,
    Decode(t.package_cf,  '-', null, t.package_cf) PackageCF,
    Decode(t.f56_parameter , '-', null, t.f56_parameter) F56Parameter,
    Decode(t.fourd_report , '-', null, t.fourd_report) FourDReport,
    Decode(t.special_characteristics , '-', null, t.special_characteristics) SpecialCharacteristics,
    t.lds_id LdsID,
    t.calc_created CalcCreated,
    t.ilds_id ILdsID,
    t.spc_com_extern SpcComExtern,
    t.spc_com_intern SpcComIntern,
    t.accepct_flag AcceptFlag,
    t."channel_state" ChState,
    t.updated_by UpdatedBy,
    t.spec_target_origin SpecTargetOrigin,
    t.viol_count ViolCount,
    to_binary_double(t.ext_ma_mv) ExtMaMV,
    to_binary_double(t.ext_ewma_mv) ExtEwmaMV,
    to_binary_double(t.ext_ms_mv) ExtMsMV,
    t.out_of_order OutOfOrder,
    t.ewma_s EwmaS, 
    t.ewma_r EwmaR,
    t.calc2_id Calc2ID,
    t.limit_enable LimitEnable,
    t.ext_ewma_mv_lcl ExtEwmaMVLCL,
    t.ext_ewma_mv_center ExtEwmaMVCenter,
    t.ext_ewma_mv_ucl ExtEwmaMVUCL,
    t.ext_ma_mv_lcl ExtMaMVLCL,
    t.ext_ma_mv_center ExtMaMVCenter,
    t.ext_ma_mv_ucl ExtMaMVUCL,
    t.ewma_s_lcl EwmaSLCL, 
    t.ewma_s_center EwmaSCenter, 
    t.ewma_s_ucl EwmaSUCL,
    t.ewma_r_lcl EwmaRLCL,
    t.ewma_r_center EwmaRCenter,
    t.ewma_r_ucl EwmaRUCL, 
    t.ext_ms_mv_lcl ExtMSMVLCL,
    t.ext_ms_mv_center ExtMSMVCenter, 
    t.ext_ms_mv_ucl ExtMSMVUCL,
    t.cl_origin ClOrigin,
    t.mv_lal MVLal,
    t.mv_ual MVUal,
    t.raw_lal RawLal,
    t.raw_ual RawUal,
    t.sigma_lal SigmaLal,
    t.sigma_ual SigmaUal,
    t.range_lal RangeLal,
    t.range_ual RangeUal,
    t.ext_spec_lower ExtSpecLower,
    t.ext_spec_upper ExtSpecUpper,
    t.ext_spec_lim_enable ExtSpecLimEnable,
    t."CalculationStrategy" CalculationStrategy,
    t.ch_id ChannelId,
    t.ckc_id CkcId,
    t.ch_name ChannelName,
    t.ch_descr ChannelDescr,
    t.is_calc_param IsCalcParam,  
    'BE' SpaceInstanceName,
    'TIJ' Sitekey, -- to here
    'Rawvalueslist' BreakPoint,
    t.sample_id SampleId,
    t.rv_seq_num Seqnr,
    t.raw_value Value,
    t.external_flagged ExternalFlagged, 
    t.internal_flagged InternalFlagged,
    t.internal_comment InternalComment,
    t.num_violations NumViolations,
    t.violation_comments ViolationComments,
    t.violation_list ViolationList,
    t.primary_violation PrimaryViolation,
    t.primary_violation_comments PrimaryViolationComments
FROM SPACEODS.V_PADS_SPC_TIJ t
 where t.lotid <> '-'
   and t.updated > :StartTime
   and t.updated <= :EndTime
  -- and t.lotid = '104O0R5.I01'
  --and PKey = 'TIJ:BE:104O0R5.I01:Plastic_Platinado:SnComposition_Percentage:1039:2911176:0'
 order by t.lotid,
   t.area,
   t.parameter_name,
   t.ch_id,
   t.sample_id,
   t.ckc_id
