select t.parameter_name ||':'|| t.ch_id ||':' || t.sample_id || ':' || t.ckc_id  as "PKey",
    t.parameter_name "ParameterName",
    t.parameter_unit "ParameterUnit",
    t.sample_date "SampleTimestamp",
    t.sample_date_utc "SampleTimestampUtc",
    t.ext_sample_size "SampleSize",
    cast(t.ext_sigma as varchar(20)) "Sigma",
    cast(t.ext_mv as varchar(20)) "Mean",
    cast(t.ext_median as varchar(20)) "Median",
    cast(t.ext_min as varchar(20)) "Min",
    cast(t.ext_max as varchar(20)) "Max",
    cast(t.ext_q1 as varchar(20)) "Q1",
    cast(t.ext_q3 as varchar(20)) "Q3",
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) "MeanCntrlLow",
    cast(to_number(t.ext_mv_center) as FLOAT(49)) "MeanCntrlTarget",
    cast(to_number(t.ext_mv_ucl ) as FLOAT(49)) "MeanCntrlHigh",
    cast(to_number(t.ext_raw_lcl ) as FLOAT(49)) "CntrlLow",
    cast(to_number(t.ext_raw_center) as FLOAT(49)) "CntrlTarget",
    cast(to_number(t.ext_raw_ucl ) as FLOAT(49)) "CntrlHigh",
    cast(to_number(t.ext_range_lcl ) as FLOAT(49)) "RangeCntrlLow",
    cast(to_number(t.ext_range_center ) as FLOAT(49)) "RangeCntrlTarget",
    cast(to_number(t.ext_range_ucl ) as FLOAT(49)) "RangeCntrlHigh",
    cast(to_number(t.ext_sigma_lcl ) as FLOAT(49)) "SigmaCntrlLow",
    cast(to_number(t.ext_sigma_center ) as FLOAT(49)) "SigmaCntrlTarget",
    cast(to_number(t.ext_sigma_ucl ) as FLOAT(49)) "SigmaCntrlHigh",
    cast(to_number(t.spec_lower ) as FLOAT(49)) "SpecLow",
    cast(to_number(t.spec_target ) as FLOAT(49)) "SpecTarget",
    cast(to_number(t.spec_upper ) as FLOAT(49)) "SpecHigh",

    t.mv_ucl_enabled "CtrlMeanHighEnabled",
    t.mv_lcl_enabled "CtrlMeanLowEnabled",
    t.mv_center_enabled "CtrlMeanTargetEnabled",
    t.raw_lcl_enabled "CtrlLowEnabled",
    t.raw_center_enabled "CtrlCenterEnabled",
    t.raw_ucl_enabled "CtrlHighEnabled",
    t.range_lcl_enabled "CtrlRangeLowEnabled",
    t.range_center_enabled "CtrlRangeCenterEnabled",
    t.range_ucl_enabled "CtrlRangeHighEnabled",
    t.sigma_lcl_enabled "CtrlSigmaLowEnabled",
    t.sigma_center_enabled "CtrlSigmaCenterEnabled",
    t.sigma_ucl_enabled "CtrlSigmaHighEnabled",
    t.spec_lower_enabled "SpecLowEnabled",
    t.spec_upper_enabled "SpecHighEnabled",
    t.created "CreatedTimestamp",
    t.created_Utc "CreatedTimestampUtc",
    t.updated "UpdatedTimestamp",
    t.updated_utc "UpdatedTimestampUtc",
    t.rv_store_flag "RvStoreFlag",

    -- All decodes were removed and just the exval and daval return. Mapping will be done on PADS side
    t.exval_00 "exval_00",
    t.exval_01 "exval_01",
    t.exval_02 "exval_02",
    t.exval_03 "exval_03",
    t.exval_04 "exval_04",
    t.exval_05 "exval_05",
    t.exval_06 "exval_06",
    t.exval_07 "exval_07",
    t.exval_08 "exval_08",
    t.exval_09 "exval_09",
    t.exval_10 "exval_10",
    t.exval_11 "exval_11",
    t.exval_12 "exval_12",
    t.exval_13 "exval_13",
    t.exval_14 "exval_14",
    t.exval_15 "exval_15",
    t.exval_16 "exval_16",
    t.exval_17 "exval_17",
    t.exval_18 "exval_18",
    t.exval_19 "exval_19",
    t.daval_00 "daval_00",
    t.daval_01 "daval_01",
    t.daval_02 "daval_02",
    t.daval_03 "daval_03",
    t.daval_04 "daval_04",
    t.daval_05 "daval_05",
    t.daval_06 "daval_06",
    t.daval_07 "daval_07",
    t.daval_08 "daval_08",
    t.daval_09 "daval_09",
    t.daval_10 "daval_10",
    t.daval_11 "daval_11",
    t.daval_12 "daval_12",
    t.daval_13 "daval_13",
    t.daval_14 "daval_14",
    t.daval_15 "daval_15",
    t.daval_16 "daval_16",
    t.daval_17 "daval_17",
    t.daval_18 "daval_18",
    t.daval_19 "daval_19",
    t.lds_id "lds_id",
    t.ch_id "ChannelId",
    t.ckc_id "CkcId",
    t.ch_name "ChannelName",
    t.ch_descr "ChannelDescr",
    t.is_calc_param "IsCalcParam",

    -- Customer fields: Mapping will be done on PADS side
    t.cf_value_00 "cf_value_00", 
    t.cf_value_01 "cf_value_01",
    t.cf_value_02 "cf_value_02", 
    t.cf_value_03 "cf_value_03", 
    t.cf_value_04 "cf_value_04", 
    t.cf_value_05 "cf_value_05", 
    t.cf_value_06 "cf_value_06", 
    t.cf_value_07 "cf_value_07", 
    t.cf_value_08 "cf_value_08",
    t.cf_value_09 "cf_value_09",
    t.cf_value_10 "cf_value_10",
    t.cf_value_11 "cf_value_11", 
    t.cf_value_12 "cf_value_12", 
    t.cf_value_13 "cf_value_13", 
    t.cf_value_14 "cf_value_14", 
    t.cf_value_15 "cf_value_15", 
    t.cf_value_16 "cf_value_16", 
    t.cf_value_17 "cf_value_17", 
    t.cf_value_18 "cf_value_18",
    t.cf_value_19 "cf_value_19",
    t.cf_value_20 "cf_value_20",
    t.cf_value_21 "cf_value_21", 
    t.cf_value_22 "cf_value_22", 
    t.cf_value_23 "cf_value_23", 
    t.cf_value_24 "cf_value_24", 
    t.cf_value_25 "cf_value_25", 
    t.cf_value_26 "cf_value_26", 
    t.cf_value_27 "cf_value_27", 
    t.cf_value_28 "cf_value_28",
    t.cf_value_29 "cf_value_29",
    t.cf_value_30 "cf_value_30",
    t.cf_value_31 "cf_value_31", 
    t.cf_value_32 "cf_value_32", 
    t.cf_value_33 "cf_value_33", 
    t.cf_value_34 "cf_value_34", 
    t.cf_value_35 "cf_value_35", 
    t.cf_value_36 "cf_value_36", 
    t.cf_value_37 "cf_value_37", 
    t.cf_value_38 "cf_value_38",
    t.cf_value_39 "cf_value_39",
    t.cf_value_40 "cf_value_40",
    t.cf_value_41 "cf_value_41", 
    t.cf_value_42 "cf_value_42", 
    t.cf_value_43 "cf_value_43", 
    t.cf_value_44 "cf_value_44", 
    t.cf_value_45 "cf_value_45", 
    t.cf_value_46 "cf_value_46", 
    t.cf_value_47 "cf_value_47", 
    t.cf_value_48 "cf_value_48",
    t.cf_value_49 "cf_value_49",
  
    -- DATALAKE Properties
    t.lds_id "LdsID",
    t.calc_created "CalcCreated",
    t.channel_type "ChannelType",
    t.ilds_id "ILdsID",
    t.spc_com_extern "SpcComExtern",
    t.spc_com_intern "SpcComIntern",
    t.accepct_flag "AcceptFlag",
    t.channel_state "ChState",
    t.updated_by "UpdatedBy",
    t.spec_target_origin "SpecTargetOrigin",
    t.viol_count "ViolCount",
    to_binary_double(t.ext_ma_mv) "ExtMaMV",
    to_binary_double(t.ext_ewma_mv) "ExtEwmaMV",
    to_binary_double(t.ext_ms_mv) "ExtMsMV",
    t.out_of_order "OutOfOrder",
    to_binary_double(t.ewma_s) "EwmaS", 
    to_binary_double(t.ewma_r) "EwmaR",
    t.calc2_id "Calc2ID",
    t.limit_enable "LimitEnable",
    t.ext_ewma_mv_lcl "ExtEwmaMVLCL",
    t.ext_ewma_mv_center "ExtEwmaMVCenter",
    t.ext_ewma_mv_ucl "ExtEwmaMVUCL",
    t.ext_ma_mv_lcl "ExtMaMVLCL",
    t.ext_ma_mv_center "ExtMaMVCenter",
    t.ext_ma_mv_ucl "ExtMaMVUCL",
    t.ewma_s_lcl "EwmaSLCL", 
    t.ewma_s_center "EwmaSCenter", 
    t.ewma_s_ucl "EwmaSUCL",
    t.ewma_r_lcl "EwmaRLCL",
    t.ewma_r_center "EwmaRCenter",
    t.ewma_r_ucl "EwmaRUCL", 
    t.ext_ms_mv_lcl "ExtMSMVLCL",
    t.ext_ms_mv_center "ExtMSMVCenter", 
    t.ext_ms_mv_ucl "ExtMSMVUCL",
    t.cl_origin "ClOrigin",
    t.mv_lal "MVLal",
    t.mv_ual "MVUal",
    t.raw_lal "RawLal",
    t.raw_ual "RawUal",
    t.sigma_lal "SigmaLal",
    t.sigma_ual "SigmaUal",
    t.range_lal "RangeLal",
    t.range_ual "RangeUal",
    t.ext_spec_lower "ExtSpecLower",
    t.ext_spec_upper "ExtSpecUpper",
    t.ext_spec_lim_enable "ExtSpecLimEnable",
    t.CalculationStrategy "CalculationStrategy",

    -- Fake Raw Value Attributes
    t.sample_id "SampleId",
    t.external_flagged "ExternalFlagged",
    t.internal_flagged "InternalFlagged",
    t.internal_comment "InternalComment",
    t.num_violations "NumViolations",
    t.violation_comments "ViolationComments",
    t.violation_list "ViolationList",
    t.primary_violation "PrimaryViolation",
    t.primary_violation_comments "PrimaryViolationComments",

    -- Raw Value Attributes
    t.rv_seq_num "Seqnr",
    to_binary_double(t.raw_value) "Value",

    -- Raw Value Flexible Attributes: Mapping will be done on PADS side
    t.raw_exval_00 "Raw_Exval_00",
    t.raw_exval_01 "Raw_Exval_01",
    t.raw_exval_02 "Raw_Exval_02",
    t.raw_exval_03 "Raw_Exval_03",
    t.raw_exval_04 "Raw_Exval_04",
    t.raw_exval_05 "Raw_Exval_05",
    t.raw_exval_06 "Raw_Exval_06",
    t.raw_exval_07 "Raw_Exval_07",
    t.raw_exval_08 "Raw_Exval_08",
    t.raw_exval_09 "Raw_Exval_09",
    t.raw_exval_10 "Raw_Exval_10",
    t.raw_exval_11 "Raw_Exval_11",
    t.raw_exval_12 "Raw_Exval_12",
    t.raw_exval_13 "Raw_Exval_13",
    t.raw_exval_14 "Raw_Exval_14",
    t.raw_exval_15 "Raw_Exval_15",
    t.raw_exval_16 "Raw_Exval_16",
    t.raw_exval_17 "Raw_Exval_17",
    t.raw_exval_18 "Raw_Exval_18",
    t.raw_exval_19 "Raw_Exval_19",
    t.raw_daval_00 "Raw_Daval_00",
    t.raw_daval_01 "Raw_Daval_01",
    t.raw_daval_02 "Raw_Daval_02",
    t.raw_daval_03 "Raw_Daval_03",
    t.raw_daval_04 "Raw_Daval_04",
    t.raw_daval_05 "Raw_Daval_05",
    t.raw_daval_06 "Raw_Daval_06",
    t.raw_daval_07 "Raw_Daval_07",
    t.raw_daval_08 "Raw_Daval_08",
    t.raw_daval_09 "Raw_Daval_09",
    t.raw_daval_10 "Raw_Daval_10",
    t.raw_daval_11 "Raw_Daval_11",
    t.raw_daval_12 "Raw_Daval_12",
    t.raw_daval_13 "Raw_Daval_13",
    t.raw_daval_14 "Raw_Daval_14",
    t.raw_daval_15 "Raw_Daval_15",
    t.raw_daval_16 "Raw_Daval_16",
    t.raw_daval_17 "Raw_Daval_17",
    t.raw_daval_18 "Raw_Daval_18",
    t.raw_daval_19 "Raw_Daval_19"

from #ViewName# t
