//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceFE.RBG.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceFE.RBG.PADS.Module.Tests.Properties.LotResources", typeof(LotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:3A110879:SPACEAGGED1:RBG:FE:WLADR:8667:K84002:ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///        &quot;SystemLog&quot;: {
        ///            &quot;JobRunId&quot;: &quot;1&quot;
        ///        },
        ///        &quot;Document&quot;: {
        ///            &quot;Version&quot;: &quot;1.0&quot;,
        ///            &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///            &quot;Repetition&quot;: {
        ///                &quot;_id&quot;: &quot;0&quot;,
        ///                &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///            }
        ///        },
        ///    &quot;ProductionAction&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdoc {
            get {
                return ResourceManager.GetString("PADSdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Meas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocInvalidRawvalues {
            get {
                return ResourceManager.GetString("PADSdocInvalidRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Meas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocNoMeasurementAggregs {
            get {
                return ResourceManager.GetString("PADSdocNoMeasurementAggregs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:3A110879:SPACEAGGED1:RBG:FE:WLADR:8667:K84002:ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocNotSameParam {
            get {
                return ResourceManager.GetString("PADSdocNotSameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Meas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocNotSameRawvalues {
            get {
                return ResourceManager.GetString("PADSdocNotSameRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Meas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocSameRawvalues {
            get {
                return ResourceManager.GetString("PADSdocSameRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;SystemLog&quot;: {
        ///        &quot;JobRunId&quot;: &quot;1&quot;,
        ///        &quot;DocCreatedTimestampUtc&quot;: &quot;2021-09-14T21:51:04.475Z&quot;,
        ///        &quot;DocUpdatedTimestampUtc&quot;: &quot;2021-09-14T21:51:25.248Z&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocwithViolations {
            get {
                return ResourceManager.GetString("PADSdocwithViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;SystemLog&quot;: {
        ///        &quot;JobRunId&quot;: &quot;1&quot;,
        ///        &quot;DocCreatedTimestampUtc&quot;: &quot;2021-09-14T21:51:04.475Z&quot;,
        ///        &quot;DocUpdatedTimestampUtc&quot;: &quot;2021-09-14T21:51:25.248Z&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocwithViolationswithoutmeas {
            get {
                return ResourceManager.GetString("PADSdocwithViolationswithoutmeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewInvalidrawvalues {
            get {
                return ResourceManager.GetString("TestCreateNewInvalidrawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewInValidWafer {
            get {
                return ResourceManager.GetString("TestCreateNewInValidWafer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewNoMeasurementAggregs {
            get {
                return ResourceManager.GetString("TestCreateNewNoMeasurementAggregs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewNoMeasurementAggregs1 {
            get {
                return ResourceManager.GetString("TestCreateNewNoMeasurementAggregs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreFalse {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewValidWafer {
            get {
                return ResourceManager.GetString("TestCreateNewValidWafer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewViolations {
            get {
                return ResourceManager.GetString("TestCreateNewViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewViolationswithoutmeas {
            get {
                return ResourceManager.GetString("TestCreateNewViolationswithoutmeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:9&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateambiguityfalse {
            get {
                return ResourceManager.GetString("TestUpdateambiguityfalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:9&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateambiguitytrueckc0 {
            get {
                return ResourceManager.GetString("TestUpdateambiguitytrueckc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateInvalidRawvalues {
            get {
                return ResourceManager.GetString("TestUpdateInvalidRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNotSameRawvalues {
            get {
                return ResourceManager.GetString("TestUpdateNotSameRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateSameRawvalues {
            get {
                return ResourceManager.GetString("TestUpdateSameRawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659434:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateValidWafer {
            get {
                return ResourceManager.GetString("TestUpdateValidWafer", resourceCulture);
            }
        }
    }
}
