//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceFE.RBG.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WaferResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WaferResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceFE.RBG.PADS.Module.Tests.Properties.WaferResources", typeof(WaferResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Motherlot:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,    
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckDoc {
            get {
                return ResourceManager.GetString("CheckDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:3A110879:SPACEAGGED1:RBG:FE:WLADR:8667:K84002:ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///    &quot;SystemLog&quot;: {
        ///        &quot;JobRunId&quot;: &quot;1&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lotdoc {
            get {
                return ResourceManager.GetString("Lotdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:3A110879:SPACEAGGED1:RBG:FE:WLADR:8667:K84002:ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LotdocInvalidValues {
            get {
                return ResourceManager.GetString("LotdocInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:3A110879:SPACEAGGED1:RBG:FE:WLADR:8667:K84002:ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lotdocisambigioustrue {
            get {
                return ResourceManager.GetString("Lotdocisambigioustrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;SystemLog&quot;: {
        ///        &quot;JobRunId&quot;: &quot;1&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LotDocRvstoreFalse {
            get {
                return ResourceManager.GetString("LotDocRvstoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;Measlot:3A110879:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;SystemLog&quot;: {
        ///        &quot;JobRunId&quot;: &quot;1&quot;
        ///    },
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LotDocRvstoreTrue {
            get {
                return ResourceManager.GetString("LotDocRvstoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Motherlot:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,    
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdoc {
            get {
                return ResourceManager.GetString("PADSdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;MotherlotWafer:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 7:42:40 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;MotherlotWafer:3A110879:01&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string padsdoc1 {
            get {
                return ResourceManager.GetString("padsdoc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///    &quot;_id&quot;: &quot;MotherlotWafer:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 7:42:40 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;MotherlotWafer:3A110879:01&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocckcgt0null {
            get {
                return ResourceManager.GetString("PADSdocckcgt0null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Motherlot:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocRvStoreFalse {
            get {
                return ResourceManager.GetString("PADSdocRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;_id&quot;: &quot;Motherlot:3A110879:01:SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;1/8/2021 8:18:18 AM&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///        &quot;_id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;_id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PADSdocRvStoreTrue {
            get {
                return ResourceManager.GetString("PADSdocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEAGG1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewInvalidrawvalues {
            get {
                return ResourceManager.GetString("TestCreateNewInvalidrawvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///    &quot;ProductionAction&quot;: {
        ///        &quot;Type&quot;: &quot;SpaceAction&quot;,
        ///        &quot;Id&quot;: &quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///    },
        ///    &quot;Item&quot;: {
        ///        &quot;Id&quot;: &quot;Measlot:3A110879&quot;,
        ///        &quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///        &quot;Type&quot;: &quot;Lot&quot;
        ///    },
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Lot&quot;: &quot;3A110879&quot;,
        ///        &quot;ParameterName&quot;: &quot;WARPAGE&quot;,
        ///        &quot;ParameterOper&quot;: &quot;8667&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;WLADR&quot;,
        ///        &quot;SiteK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewInvalidValues {
            get {
                return ResourceManager.GetString("TestCreateNewInvalidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;IdSource&quot;:&quot;SPACEACT1:RBG:FE:3A110879:WLADR:8667:WARPAGE:161310:522659473:0&quot;,
        ///	&quot;ProductionAction&quot;:
        ///	{
        ///		&quot;Type&quot;:&quot;SpaceAction&quot;,
        ///		&quot;Id&quot;:&quot;SPACEACT1:RBG:FE:WLADR:8667:WARPAGE:161310&quot;
        ///	},
        ///	&quot;Item&quot;:
        ///	{
        ///		&quot;Id&quot;:&quot;Measlot:3A110879&quot;,
        ///		&quot;IdSystemName&quot;:&quot;Measlot&quot;,
        ///		&quot;Type&quot;:&quot;Lot&quot;
        ///	},
        ///	&quot;Data_flat_Metadata&quot;:
        ///	{
        ///		&quot;Lot&quot;:&quot;3A110879&quot;,
        ///		&quot;ParameterName&quot;:&quot;WARPAGE&quot;,
        ///		&quot;ParameterOper&quot;:&quot;8667&quot;,
        ///		&quot;ParameterFacility&quot;:&quot;WLADR&quot;,
        ///		&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///		&quot;ChannelId&quot;:161310,
        ///		&quot;SpaceInstanceName&quot;:&quot;FE&quot;,
        ///		&quot;CreatedTimestam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewValidWafer {
            get {
                return ResourceManager.GetString("TestCreateNewValidWafer", resourceCulture);
            }
        }
    }
}
