//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.WAR.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.WAR.PADS.Module.Tests.Properties.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SearchPatterns&quot;: {
        ///        &quot;SpaceKey&quot;: &quot;Measlot:88888888:SPACEAGGED3:WAR:BE:HD:Paste Printer::ProcessControl:1.0&quot;,
        ///        &quot;TimeGroup&quot;: &quot;0&quot;,
        ///        &quot;SiteKey&quot;: &quot;RBG&quot;
        ///    },
        ///    &quot;_id&quot;: &quot;Measlot::SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///    &quot;Document&quot;: {
        ///        &quot;Version&quot;: &quot;1.0&quot;,
        ///        &quot;Type&quot;: &quot;ProcessControl&quot;,
        ///        &quot;Repetition&quot;: {
        ///            &quot;_id&quot;: &quot;0&quot;,
        ///            &quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:37.000Z&quot;
        ///        }
        ///    },
        ///    &quot;ProductionAction&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT3:WAR:BE:88888888:HD:Paste Printer:Parameter:49689:219254629:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;ChannelId&quot;: 49689,
        ///        &quot;SourceDataLevel&quot;: &quot;C&quot;,
        ///        &quot;ChannelName&quot;: &quot;diameter_All_Rudolph&quot;,
        ///        &quot;ChannelDescr&quot;: &quot;Created from LDS \nexclude list by \naction &apos;Create SPC Channel&apos;&quot;,
        ///        &quot;RvStoreFlag&quot;: &quot;Y&quot;,
        ///        &quot;SiteKey&quot;: &quot;WAR&quot;,
        ///        &quot;ParameterOper&quot;: &quot;Paste Printer&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;Plant&quot;: &quot;Hybrid&quot;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
    }
}
