//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceNew.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceNew.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // This is a simple method and attribute definition in the abbreviated form
        ///    // e.g. AbbreviatedMethodInvokeMapping.TwoInputParameters.JoinStrings.Equipment translates to
        ///    // x.Equipment = JoinStrings(t.Equipment, u.Equipment)
        ///    // By using this definition attributes will be dynamically assigned if class
        ///    // object x has your property. If x has the property then the method will be invoked
        ///    // by reflection using the defined attributes in the same order. The result will be
        ///    // a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MethodInvokeConfig {
            get {
                return ResourceManager.GetString("MethodInvokeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // All daval_ and exval_ attribute names which correspond with
        ///    // this section are assigned to the Data_flat_Metadata section
        ///    // All other daval_ and exval_ attributes are assigned to the
        ///    // Data_flat_StrangeMetadata section
        ///    &quot;Data_flat_Metadata&quot;: [
        ///        &quot;ParameterFacility&quot;,
        ///        &quot;Lot&quot;,
        ///        &quot;SiteKey&quot;,
        ///        &quot;SpaceInstanceName&quot;,
        ///        &quot;Route&quot;,
        ///        &quot;SampleTimestamp&quot;,
        ///        &quot;SampleTimestampUtc&quot;,
        ///        &quot;Shift&quot;,
        ///        &quot;Process&quot;,
        ///        &quot;Measlot&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyPlacementConfig {
            get {
                return ResourceManager.GetString("PropertyPlacementConfig", resourceCulture);
            }
        }
    }
}
