//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceFE.RBG.Source.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceFE.RBG.Source.Module.Tests.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT1:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;ProcessEquipment&quot;: &quot;PE&quot;,
        ///        &quot;Design&quot;: &quot;Design&quot;,
        ///        &quot;Layer&quot;: &quot;Layer&quot;,
        ///        &quot;ProcessBatch&quot;: &quot;ProcessBatch&quot;,
        ///        &quot;MeasurementBatch&quot;: &quot;0&quot;,
        ///        &quot;Recipe&quot;: &quot;recipe&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;PG&quot;,
        ///        &quot;EquipmentType&quot;: &quot;equipmenttype&quot;,
        ///        &quot;ProcessLine&quot;: &quot;PL&quot;,
        ///        &quot;Lot&quot;: &quot;RU123456&quot;,
        ///        &quot;ParameterName&quot;: &quot;paramname&quot;,
        ///        &quot;ParameterOper&quot;: &quot;2345&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;1702&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a {
            get {
                return ResourceManager.GetString("ExpectedE4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SPS_Number&quot;: &quot;sps&quot;,
        ///    &quot;ProcessGroup&quot;: &quot;PG&quot;,
        ///    &quot;Recipe&quot;: &quot;recipe&quot;,
        ///    &quot;ProcessLine&quot;: &quot;PL&quot;,
        ///    &quot;ProcessEquipment&quot;: &quot;PE&quot;,
        ///    &quot;MeasurementEquipmentType&quot;: &quot;equipmenttype&quot;,
        ///    &quot;Design&quot;: &quot;Design&quot;,
        ///    &quot;Layer&quot;: &quot;Layer&quot;,
        ///    &quot;MeasurementBatch&quot;: &quot;0&quot;,
        ///    &quot;ProcessBatch&quot;: &quot;ProcessBatch&quot;,
        ///    &quot;MotherlotWafer&quot;: &quot;RU123456.03&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;WaferName&quot;: &quot;RU123456.03&quot;,
        ///            &quot;X&quot;: &quot;14.5&quot;,
        ///            &quot;Y&quot;: &quot;54.7&quot;,
        ///            &quot;GOF&quot;: &quot;0.2&quot;,
        ///            &quot;Sl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord {
            get {
                return ResourceManager.GetString("SourceRecord", resourceCulture);
            }
        }
    }
}
