//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.RBG.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WaferResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WaferResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.RBG.PADS.Module.Tests.Properties.WaferResources", typeof(WaferResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;_id&quot;: &quot;MotherlotWafer:3A140739:22:SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///	&quot;Document&quot;: {
        ///		&quot;Version&quot;: &quot;1.0&quot;,
        ///		&quot;Type&quot;: &quot;ProcessControl&quot;,
        ///		&quot;Repetition&quot;: {
        ///			&quot;_id&quot;: &quot;0&quot;,
        ///			&quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:38.000Z&quot;
        ///		}
        ///	},
        ///	&quot;ProductionAction&quot;: {
        ///		&quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///		&quot;_id&quot;: &quot;SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689&quot;
        ///	},
        ///	&quot;Item&quot;: {
        ///		&quot;_id&quot;: &quot;MotherlotWafer:3A140739:22&quot;,
        ///		&quot;IdSystemName&quot;: &quot;MotherlotWafer&quot;,
        ///		&quot;Type&quot;: &quot;Wafer&quot;
        ///	},
        ///	&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckDoc {
            get {
                return ResourceManager.GetString("CheckDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;_id&quot;: &quot;Measlot:3A140739:SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///	&quot;Document&quot;: {
        ///		&quot;Version&quot;: &quot;1.0&quot;,
        ///		&quot;Type&quot;: &quot;ProcessControl&quot;,
        ///		&quot;Repetition&quot;: {
        ///			&quot;_id&quot;: &quot;0&quot;,
        ///			&quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:37.000Z&quot;
        ///		}
        ///	},
        ///	&quot;ProductionAction&quot;: {
        ///		&quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///		&quot;_id&quot;: &quot;SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689&quot;
        ///	},
        ///	&quot;Item&quot;: {
        ///		&quot;_id&quot;: &quot;Measlot:3A140739&quot;,
        ///		&quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///		&quot;Type&quot;: &quot;Lot&quot;
        ///	},
        ///	&quot;SystemLog&quot;: {
        ///		&quot;SiteKey&quot;: &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;_id&quot;: &quot;Measlot:3A140739:SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///	&quot;Document&quot;: {
        ///		&quot;Version&quot;: &quot;1.0&quot;,
        ///		&quot;Type&quot;: &quot;ProcessControl&quot;,
        ///		&quot;Repetition&quot;: {
        ///			&quot;_id&quot;: &quot;0&quot;,
        ///			&quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:37.000Z&quot;
        ///		}
        ///	},
        ///	&quot;ProductionAction&quot;: {
        ///		&quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///		&quot;_id&quot;: &quot;SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689&quot;
        ///	},
        ///	&quot;Item&quot;: {
        ///		&quot;_id&quot;: &quot;Measlot:3A140739&quot;,
        ///		&quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///		&quot;Type&quot;: &quot;Lot&quot;
        ///	},
        ///	&quot;SystemLog&quot;: {
        ///		&quot;SiteKey&quot;: &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreTrue {
            get {
                return ResourceManager.GetString("PadsDocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;_id&quot;: &quot;Measlot:3A140739:SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///	&quot;Document&quot;: {
        ///		&quot;Version&quot;: &quot;1.0&quot;,
        ///		&quot;Type&quot;: &quot;ProcessControl&quot;,
        ///		&quot;Repetition&quot;: {
        ///			&quot;_id&quot;: &quot;0&quot;,
        ///			&quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:37.000Z&quot;
        ///		}
        ///	},
        ///	&quot;ProductionAction&quot;: {
        ///		&quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///		&quot;_id&quot;: &quot;SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689&quot;
        ///	},
        ///	&quot;Item&quot;: {
        ///		&quot;_id&quot;: &quot;Measlot:3A140739&quot;,
        ///		&quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///		&quot;Type&quot;: &quot;Lot&quot;
        ///	},
        ///	&quot;SystemLog&quot;: {
        ///		&quot;SiteKey&quot;: &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocUpdateNewParam {
            get {
                return ResourceManager.GetString("PadsDocUpdateNewParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;_id&quot;: &quot;Measlot:3A140739:SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689:ProcessControl:1.0&quot;,
        ///	&quot;Document&quot;: {
        ///		&quot;Version&quot;: &quot;1.0&quot;,
        ///		&quot;Type&quot;: &quot;ProcessControl&quot;,
        ///		&quot;Repetition&quot;: {
        ///			&quot;_id&quot;: &quot;0&quot;,
        ///			&quot;IdBaseValue&quot;: &quot;2021-08-05T22:58:37.000Z&quot;
        ///		}
        ///	},
        ///	&quot;ProductionAction&quot;: {
        ///		&quot;Type&quot;: &quot;SpaceAggregation&quot;,
        ///		&quot;_id&quot;: &quot;SPACEAGG2:RBG:BE:HFICR::bumpdiameter_All_bumps:49689&quot;
        ///	},
        ///	&quot;Item&quot;: {
        ///		&quot;_id&quot;: &quot;Measlot:3A140739&quot;,
        ///		&quot;IdSystemName&quot;: &quot;Measlot&quot;,
        ///		&quot;Type&quot;: &quot;Lot&quot;
        ///	},
        ///	&quot;SystemLog&quot;: {
        ///		&quot;SiteKey&quot;: &quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocUpdateNewParamRvFalse {
            get {
                return ResourceManager.GetString("PadsDocUpdateNewParamRvFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT1:RBG:BE:3A140739:HFICR:-:bumpdiameter_All_bumps:49689:219254629:0&quot;,
        ///&quot;Data_flat_Metadata&quot;:
        ///{
        ///&quot;Segment&quot;:&quot;SCCM&quot;,
        ///&quot;GroupId&quot;:&quot;RBGEW273&quot;,
        ///&quot;Lot&quot;:&quot;3A140739&quot;,
        ///&quot;ParameterName&quot;:&quot;bumpdiameter_All_bumps&quot;,
        ///&quot;ParameterUnit&quot;:&quot;µm&quot;,
        ///&quot;ParameterFacility&quot;:&quot;HFICR&quot;,
        ///&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///&quot;ChannelId&quot;:&quot;49689&quot;,
        ///&quot;SpaceInstanceName&quot;:&quot;BE&quot;,
        ///&quot;CreatedTimestampUtc&quot;:&quot;2021-08-05T22:58:25Z&quot;,
        ///&quot;CreatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestampUtc&quot;:&quot;2021-08-05T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT1:RBG:BE:3A140739:HFICR:-:bumpdiameter_All_bumps:49689:219254629:0&quot;,
        ///&quot;Data_flat_Metadata&quot;:
        ///{
        ///&quot;Segment&quot;:&quot;SCCM&quot;,
        ///&quot;GroupId&quot;:&quot;RBGEW273&quot;,
        ///&quot;Lot&quot;:&quot;3A140739&quot;,
        ///&quot;ParameterName&quot;:&quot;bumpdiameter_All_bumps&quot;,
        ///&quot;ParameterUnit&quot;:&quot;µm&quot;,
        ///&quot;ParameterFacility&quot;:&quot;HFICR&quot;,
        ///&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///&quot;ChannelId&quot;:&quot;49689&quot;,
        ///&quot;SpaceInstanceName&quot;:&quot;BE&quot;,
        ///&quot;CreatedTimestampUtc&quot;:&quot;2021-08-05T22:58:25Z&quot;,
        ///&quot;CreatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestampUtc&quot;:&quot;2021-08-05T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreTrue {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT1:RBG:BE:3A140739:HFICR:-:bumpdiameter_Some_bumps:49689:219254629:0&quot;,
        ///&quot;Data_flat_Metadata&quot;:
        ///{
        ///&quot;Segment&quot;:&quot;SCCM&quot;,
        ///&quot;GroupId&quot;:&quot;RBGEW273&quot;,
        ///&quot;Lot&quot;:&quot;3A140739&quot;,
        ///&quot;ParameterName&quot;:&quot;bumpdiameter_Some_bumps&quot;,
        ///&quot;ParameterUnit&quot;:&quot;µm&quot;,
        ///&quot;ParameterFacility&quot;:&quot;HFICR&quot;,
        ///&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///&quot;ChannelId&quot;:&quot;49689&quot;,
        ///&quot;SpaceInstanceName&quot;:&quot;BE&quot;,
        ///&quot;CreatedTimestampUtc&quot;:&quot;2021-08-05T22:58:25Z&quot;,
        ///&quot;CreatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestampUtc&quot;:&quot;2021-08-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParam {
            get {
                return ResourceManager.GetString("TestUpdateNewParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT1:RBG:BE:3A140739:HFICR:-:bumpdiameter_Some_bumps:49689:219254629:0&quot;,
        ///&quot;Data_flat_Metadata&quot;:
        ///{
        ///&quot;Segment&quot;:&quot;SCCM&quot;,
        ///&quot;GroupId&quot;:&quot;RBGEW273&quot;,
        ///&quot;Lot&quot;:&quot;3A140739&quot;,
        ///&quot;ParameterName&quot;:&quot;bumpdiameter_Some_bumps&quot;,
        ///&quot;ParameterUnit&quot;:&quot;µm&quot;,
        ///&quot;ParameterFacility&quot;:&quot;HFICR&quot;,
        ///&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///&quot;ChannelId&quot;:&quot;49689&quot;,
        ///&quot;SpaceInstanceName&quot;:&quot;BE&quot;,
        ///&quot;CreatedTimestampUtc&quot;:&quot;2021-08-05T22:58:25Z&quot;,
        ///&quot;CreatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestampUtc&quot;:&quot;2021-08-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreTrue {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreTrue", resourceCulture);
            }
        }
    }
}
