select 'RBG:BE:'|| t.lot || ':' || t.facility || ':' || t.operation || ':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
       t.parameter_name ParameterName,
       DECODE(t.parameter_unit, '-', null,t.parameter_unit) ParameterUnit,
       t.sample_date SampleDate,
       t.sample_date_utc SampleDateUtc,
       t.ext_sample_size SampleSize,
       cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl ) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl ) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl ) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl ) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center ) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl ) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl ) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center ) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl ) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower ) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target ) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper ) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_Utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    DECODE(t.rv_store_flag, '-', null, t.rv_store_flag) RvStoreFlag,
       Decode(t.facility,'-',null, t.facility) Facility,
       Decode(t.product,'-',null,  t.product) Product,
       Decode(t.product_type,'-',null, t.product_type) ProductType,
       Decode(t.salesname,'-',null,t.salesname) SalesName,
       Decode(t.package_family,'-',null,t.package_family) PackageFamily,
       Decode(t.device,'-',null,t.device) Device,
       Decode(t.package,'-',null, t.package) Package,
       Decode(t.module, '-',null, t.module) Module,
       Decode(t.route,'-',null, t.route) Route,
       Decode(t.basictype,'-',null,t.basictype) BasicType,
       Decode(t.operation,'-',null, t.operation) Operation,
       Decode(t.be_sort,'-',null,t.be_sort) BeSort,    
       Decode(t.material,'-',null,t.material) Material,
       Decode(t.measurement_equipment,'-',null,t.measurement_equipment) MeasurementEquipment,
       Decode(t.segment,'-',null,t.segment) Segment,
       Decode(t.equipment_type,'-',null, t.equipment_type) EquipmentType,
       Decode(t.group_id,'-',null,t.group_id) GroupId,
       Decode(t.wire,'-',null,t.wire) Wire,
       Decode(t.package_group,'-',null, t.package_group) PackageGroup,
       Decode(t.lot,'-',null,t.lot) Lot,
       Decode(t.package_class,'-',null,t.package_class) PackageClass,
       Decode(t.device_family,'-',null,t.device_family) DeviceFamily,
       Decode(t.user_class_1,'-',null,t.user_class_1) UserClass1,
       Decode(t.owner,'-',null,t.owner) Owner,
       Decode(t.user_class_2,'-',null,t.user_class_2) UserClass2,
       Decode(t.group_1,'-',null,t.group_1) Group1,
       Decode(t.user_class_3,'-',null,t.user_class_3) UserClass3,
       Decode(t.group_2,'-',null,t.group_2) Group2,
       Decode(t.spec_name,'-',null,t.spec_name) SpecName,
       Decode(t.group_3,'-',null,t.group_3) Group3,
       Decode(t.origin_sample_size,'-',null,t.origin_sample_size) OriginSampleSize,
       Decode(t.sample_type,'-',null,t.sample_type) SampleType,
       Decode(t.move_in_quantity,'-',null, t.move_in_quantity) MoveInQuantity,
       Decode(t.move_out_quantity,'-',null,t.move_out_quantity) MoveOutQuantity,
       Decode(t.operator_id,'-',null,t.operator_id) OperatorId,
       Decode(t.product_name,'-',null,t.product_name) ProductName,
       Decode(t.be_segment_name,'-',null,t.be_segment_name) BeSegmentName,
       Decode(t.manufacturing_wip_level,'-',null,t.manufacturing_wip_level) ManufacturingWipLevel,
       Decode(t.errorcode,'-',null, t.errorcode) ErrorCode,
       Decode(t.pin,'-',null, t.pin) Pin,
       Decode(t.data_1,'-',null,t.data_1) Data1,
       Decode(t.data_2,'-',null, t.data_2) Data2,
       Decode(t.data_3,'-',null,t.data_3) Data3,
       Decode(t.wafer_lot,'-',null,t.wafer_lot) WaferLot,
       t.ch_id ChannelId,
       t.ckc_id CkcId,
       t.ch_name ChannelName,
       t.ch_descr ChannelDescr,
       t.is_calc_param IsCalcParam,       
       'BE' SpaceInstanceName,
       'RBG' Sitekey,
       'Rawvalueslist' BreakPoint,
       t.sample_id SampleId,
       t.rv_seq_num Seqnr,
       t.raw_value Value,
       Decode(t.wafer_lot,'-',null,t.wafer_lot) WaferLot,
       t.external_flagged ExternalFlagged,
       t.internal_flagged InternalFlagged,
       t.internal_comment InternalComment,
       t.num_violations NumViolations,
       t.violation_comments ViolationComments,
       t.violation_list ViolationList,
       t.primary_violation PrimaryViolation,
       t.primary_violation_comments PrimaryViolationComments
       from spaceods.v_pads_spc_rbg_be t
where t.updated > :StartTime
and t.updated <= :EndTime
and t.lot <> '-'
order by t.lot,t.facility , t.operation ,t.parameter_name , t.ch_id, t.sample_id ,t.ckc_id 
    
