select 'MKZ:BE:' || t.lotnumber || ':' || t.facility || ':' ||
       t.operationno || ':' || t.parameter_name || ':' || t.ch_id || ':' ||
       t.sample_id || ':' || t.ckc_id as PKey,
              t.parameter_name ParameterName,
       Decode(t.parameter_unit, '-', null, t.parameter_unit) ParameterUnit,
       t.sample_date SampleDate,
       t.sample_date_utc SampleDateUtc,
       t.ext_sample_size SampleSize,
       cast(t.ext_sigma as varchar(20)) Sigma,
       cast(t.ext_median as varchar(20)) Median,
       cast(t.ext_mv as varchar(20)) Mean,
       cast(t.ext_max as varchar(20)) Max,
       cast(t.ext_min as varchar(20)) Min,
       cast(t.ext_q1 as varchar(20)) Q1,
       cast(t.ext_q3 as varchar(20)) Q3,
       cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
       cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
       cast(to_number(t.ext_mv_ucl) as FLOAT(49)) MeanCntrlHigh,
       cast(to_number(t.ext_raw_lcl) as FLOAT(49)) CntrlLow,
       cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
       cast(to_number(t.ext_raw_ucl) as FLOAT(49)) CntrlHigh,
       cast(to_number(t.ext_range_lcl) as FLOAT(49)) RangeCntrlLow,
       cast(to_number(t.ext_range_center) as FLOAT(49)) RangeCntrlTarget,
       cast(to_number(t.ext_range_ucl) as FLOAT(49)) RangeCntrlHigh,
       cast(to_number(t.ext_sigma_lcl) as FLOAT(49)) SigmaCntrlLow,
       cast(to_number(t.ext_sigma_center) as FLOAT(49)) SigmaCntrlTarget,
       cast(to_number(t.ext_sigma_ucl) as FLOAT(49)) SigmaCntrlHigh,
       cast(to_number(t.spec_lower) as FLOAT(49)) SpecLow,
       cast(to_number(t.spec_target) as FLOAT(49)) SpecTarget,
       cast(to_number(t.spec_upper) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    t.rv_store_flag RvStoreFlag,       
    Decode(t.track , '-', null, t.track) Track,
    Decode(t.machine , '-', null, t.machine) Machine,
    Decode(t.tool , '-', null, t.tool) Tool,
    Decode(t.packagekeys , '-', null, t.packagekeys) PackageKeys,
    Decode(t.category , '-', null, t.category) Category,
    Decode(t.leadframe , '-', null, t.leadframe) LeadFrame,
    Decode(t.wiresize , '-', null, t.wiresize) WireSize,
    Decode(t.diesize , '-', null, t.diesize) DieSize,
    Decode(t.solderglue , '-', null, t.solderglue) SolderGlue,
    Decode(t.eintrag , '-', null, t.eintrag) Eintrag,
    Decode(t.product , '-', null, t.product) Product,
    Decode(t.devicekeys , '-', null, t.devicekeys) DeviceKeys,
    Decode(t.lotnumber , '-', null, t.lotnumber) Lot,
    Decode(t.classification2 , '-', null, t.classification2) Classification2,
    Decode(t.line , '-', null, t.line) Line,
    Decode(t.process , '-', null, t.process) Process,
    Decode(t.familypackage , '-', null, t.familypackage) FamilyPackage,
    Decode(t.wiretype , '-', null, t.wiretype) WireType,
    Decode(t.subline , '-', null, t.subline) SubLine,
    Decode(t.diecategory , '-', null, t.diecategory) DieCategory,
    Decode(t.chiptype , '-', null, t.chiptype) ChipType,
    Decode(t.classifiction , '-', null, t.classifiction) Classification,
    Decode(t.defectcategory , '-', null, t.defectcategory) DefectCategory,
    Decode(t.characteristics , '-', null, t.characteristics) Characteristics,
    Decode(t.originofrc , '-', null, t.originofrc) OriginOfRC,
    Decode(t.facility , '-', null, t.facility) Facility,
    Decode(t.operationno , '-', null, t.operationno) Operation,
    Decode(t.type , '-', null, t.type) Type,
    Decode(t.wire , '-', null, t.wire) Wire,
    Decode(t.groupkeys , '-', null, t.groupkeys) GroupKeys,
    Decode(t.modulekeys , '-', null, t.modulekeys) ModuleKeys,
    Decode(t.sawstreet , '-', null, t.sawstreet) SawStreet,
    Decode(t.waferthickness , '-', null, t.waferthickness) WaferThickness,
    Decode(t.bladecategory , '-', null, t.bladecategory) BladeCategory,
    Decode(t.equipment , '-', null, t.equipment) Equipment,
    Decode(t.wafercharge , '-', null, t.wafercharge) WaferCharge,
    Decode(t.padsize , '-', null, t.padsize) PadSize,
    Decode(t.spctool , '-', null, t.spctool) SpcTool,
    Decode(t.toolid , '-', null, t.toolid) ToolId,
    Decode(t.variation , '-', null, t.variation) Variation,
    Decode(t.gaugeid , '-', null, t.gaugeid) GaugeID,
    Decode(t.operator , '-', null, t.operator) Operator,
    Decode(t.shift , '-', null, t.shift) Shift,
    Decode(t.cartridgeid , '-', null, t.cartridgeid) CartridgeID,
    Decode(t.grade , '-', null, t.grade) Grade,
    Decode(t.solderfeed , '-', null, t.solderfeed) SolderFeed,
    Decode(t.coding , '-', null, t.coding) Coding,
    Decode(t.sizekeys , '-', null, t.sizekeys) SizeKeys,
    Decode(t.gaugeid2 , '-', null, t.gaugeid2) GaugeID2,
    Decode(t.numberkeys , '-', null, t.numberkeys) NumberKeys,
    Decode(t.remark , '-', null, t.remark) Remark,
    Decode(t.solderfeedlength , '-', null, t.solderfeedlength) SolderFeedLength,
    Decode(t.wafernumber , '-', null, t.wafernumber) WaferNumber,
    Decode(t.rasterx , '-', null, t.rasterx) RasterX,
    Decode(t.rastery , '-', null, t.rastery) RasterY,
    Decode(t.magnification , '-', null, t.magnification) Magnification,
    Decode(t.machine1 , '-', null, t.machine1) Machine1,
    Decode(t.parameter_class , '-', null, t.parameter_class) ParameterClass,
    Decode(t.cf_comment , '-', null, t.cf_comment) CFComment,
    Decode(t.target_cpk , '-', null, t.target_cpk) TargetCpk,
    Decode(t.process_owner , '-', null, t.process_owner) ProcessOwner,
    Decode(t.segment , '-', null, t.segment) Segment,
    Decode(t.module , '-', null, t.module) Module,
    Decode(t.package , '-', null, t.package) Package,
    Decode(t.f56_parameter , '-', null, t.f56_parameter) F56Parameter,
    Decode(t.published , '-', null, t.published) Published,
    Decode(t.group_id , '-', null, t.group_id) GroupID,
    Decode(t.device , '-', null, t.device) Device,
    Decode(t.fourd_report , '-', null, t.fourd_report) FourDReport,
    Decode(t.special_characteristics , '-', null, t.special_characteristics) SpecialCharacteristics,
    t.lds_id LdsID,
    t.calc_created CalcCreated,
    t.ilds_id ILdsID,
    t.spc_com_extern SpcComExtern,
    t.spc_com_intern SpcComIntern,
    t.accepct_flag AcceptFlag,
    t.channel_state ChState,
    t.updated_by UpdatedBy,
    t.spec_target_origin SpecTargetOrigin,
    t.viol_count ViolCount,
    to_binary_double(t.ext_ma_mv) ExtMaMV,
    to_binary_double(t.ext_ewma_mv) ExtEwmaMV,
    to_binary_double(t.ext_ms_mv) ExtMsMV,
    t.out_of_order OutOfOrder,
    t.ewma_s EwmaS, 
    t.ewma_r EwmaR,
    t.calc2_id Calc2ID,
    t.limit_enable LimitEnable,
    t.ext_ewma_mv_lcl ExtEwmaMVLCL,
    t.ext_ewma_mv_center ExtEwmaMVCenter,
    t.ext_ewma_mv_ucl ExtEwmaMVUCL,
    t.ext_ma_mv_lcl ExtMaMVLCL,
    t.ext_ma_mv_center ExtMaMVCenter,
    t.ext_ma_mv_ucl ExtMaMVUCL,
    t.ewma_s_lcl EwmaSLCL, 
    t.ewma_s_center EwmaSCenter, 
    t.ewma_s_ucl EwmaSUCL,
    t.ewma_r_lcl EwmaRLCL,
    t.ewma_r_center EwmaRCenter,
    t.ewma_r_ucl EwmaRUCL, 
    t.ext_ms_mv_lcl ExtMSMVLCL,
    t.ext_ms_mv_center ExtMSMVCenter, 
    t.ext_ms_mv_ucl ExtMSMVUCL,
    t.cl_origin ClOrigin,
    t.mv_lal MVLal,
    t.mv_ual MVUal,
    t.raw_lal RawLal,
    t.raw_ual RawUal,
    t.sigma_lal SigmaLal,
    t.sigma_ual SigmaUal,
    t.range_lal RangeLal,
    t.range_ual RangeUal,
    t.ext_spec_lower ExtSpecLower,
    t.ext_spec_upper ExtSpecUpper,
    t.ext_spec_lim_enable ExtSpecLimEnable,
    t.calculationstrategy CalculationStrategy,
    t.ch_id ChannelId,
       t.ckc_id CkcId,
       t.ch_name ChannelName,
       t.channel_type ChannelType,
       t.ch_descr ChannelDescr,
       t.is_calc_param IsCalcParam,     
       'BE' SpaceInstanceName,
       'MKZ' Sitekey,
       'Rawvalueslist' BreakPoint,
       t.sample_id SampleId,
       t.rv_seq_num Seqnr,
       to_binary_double(t.raw_value) Value,
       t.external_flagged ExternalFlagged,
       t.internal_flagged InternalFlagged,
       t.internal_comment InternalComment,
       t.num_violations NumViolations,
       t.violation_comments ViolationComments,
       t.violation_list ViolationList,
       t.primary_violation PrimaryViolation,
       t.primary_violation_comments PrimaryViolationComments,
       Decode(t.machine , '-', null, t.machine) Machine,
       Decode(t.tool , '-', null, t.tool) Tool
  from SPACEODS.V_PADS_SPC_MKZ t
 where t.updated > :StartTime
and t.updated <= :EndTime
and t.lds_id = :LdsId
   and t.lotnumber <> '-'
 order by t.lotnumber,
          t.facility,
          t.operationno,
          t.parameter_name,
          t.ch_id,
          t.sample_id,
          t.ckc_id
