//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.WAR.Source.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.WAR.Source.Module.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a1 {
            get {
                return ResourceManager.GetString("ExpectedE4a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a2 {
            get {
                return ResourceManager.GetString("ExpectedE4a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a3 {
            get {
                return ResourceManager.GetString("ExpectedE4a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a4 {
            get {
                return ResourceManager.GetString("ExpectedE4a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a5 {
            get {
                return ResourceManager.GetString("ExpectedE4a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a6 {
            get {
                return ResourceManager.GetString("ExpectedE4a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a7 {
            get {
                return ResourceManager.GetString("ExpectedE4a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///        &quot;Parame [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a8 {
            get {
                return ResourceManager.GetString("ExpectedE4a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;plant&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;88888888&quot;,
        ///        &quot;Batch&quot;: &quot;batch&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;extr1, materialnumber&quot;,
        ///        &quot;ProductGroup&quot;: &quot;productgroup&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;Recipe&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;ProcessEquip&quot;,
        ///        &quot;OrderType&quot;: &quot;OrderType&quot;,
        ///        &quot;QrkGroup&quot;: &quot;QrkGroup&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;ProcessGroup&quot;,
        ///        &quot;SpcClass&quot;: &quot;SpcClass&quot;,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a9 {
            get {
                return ResourceManager.GetString("ExpectedE4a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord1 {
            get {
                return ResourceManager.GetString("SourceRecord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord10 {
            get {
                return ResourceManager.GetString("SourceRecord10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord2 {
            get {
                return ResourceManager.GetString("SourceRecord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord3 {
            get {
                return ResourceManager.GetString("SourceRecord3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord4 {
            get {
                return ResourceManager.GetString("SourceRecord4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord5 {
            get {
                return ResourceManager.GetString("SourceRecord5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord6 {
            get {
                return ResourceManager.GetString("SourceRecord6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord7 {
            get {
                return ResourceManager.GetString("SourceRecord7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord8 {
            get {
                return ResourceManager.GetString("SourceRecord8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord9 {
            get {
                return ResourceManager.GetString("SourceRecord9", resourceCulture);
            }
        }
    }
}
