//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.BAT.Source.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.BAT.Source.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &apos;BAT:BE:&apos;|| t.lot || &apos;:&apos; || t.facility || &apos;:&apos; || t.operation || &apos;:&apos; || t.parameter_name || &apos;:&apos; || t.ch_id ||&apos;:&apos; || t.sample_id || &apos;:&apos; || t.ckc_id as PKey,
        ///    t.parameter_name ParameterName,
        ///    DECODE(t.parameter_unit, &apos;-&apos;, null,t.parameter_unit) ParameterUnit,
        ///    t.sample_date SampleDate,
        ///    t.sample_date_utc SampleDateUtc,
        ///    t.ext_sample_size SampleSize,
        ///    cast(t.ext_sigma as varchar(20)) Sigma,
        ///    cast(t.ext_mv as varchar(20)) Mean,
        ///    cast(t.ext_median as varchar(20)) Median,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpaceSqlQuery {
            get {
                return ResourceManager.GetString("SpaceSqlQuery", resourceCulture);
            }
        }
    }
}
