//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.CJJ.Source.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.CJJ.Source.Module.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:pkey&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Operator&quot;: &quot;Operator&quot;,
        ///        &quot;Package&quot;: &quot;Package&quot;,
        ///        &quot;ParameterClass&quot;: &quot;ParamClass&quot;,
        ///        &quot;ProcessOwner&quot;: &quot;ProcessOwner&quot;,
        ///        &quot;TargetCpk&quot;: &quot;TargetCpk&quot;,
        ///        &quot;Segment&quot;: &quot;Segment&quot;,
        ///        &quot;Module&quot;: &quot;Module&quot;,
        ///        &quot;F56Parameter&quot;: &quot;F56Parameter&quot;,
        ///        &quot;GroupID&quot;: &quot;GroupId&quot;,
        ///        &quot;Line&quot;: &quot;HD&quot;,
        ///        &quot;ParameterName&quot;: &quot;paramname&quot;,
        ///        &quot;ParameterOper&quot;: &quot;Oper&quot;,
        ///        &quot;SiteKey&quot;: &quot;WAR&quot;,
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedE4a1 {
            get {
                return ResourceManager.GetString("ExpectedE4a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;SpecName&quot;: &quot;SpecName&quot;,
        ///    &quot;SpaceRawValues&quot;: [
        ///        {
        ///            &quot;BreakPoint&quot;: &quot;bp&quot;,
        ///            &quot;SampleId&quot;: 123456,
        ///            &quot;Seqnr&quot;: 2,
        ///            &quot;Value&quot;: 23.45,
        ///            &quot;ExternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalFlagged&quot;: &quot;N&quot;,
        ///            &quot;InternalComment&quot;: &quot;&quot;,
        ///            &quot;NumViolations&quot;: 0,
        ///            &quot;ViolationComments&quot;: &quot;viocomments&quot;,
        ///            &quot;ViolationList&quot;: &quot;violist&quot;,
        ///            &quot;PrimaryViolation&quot;: &quot;primvio&quot;,
        ///            &quot;PrimaryViolationComments&quot;: &quot;primvi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SourceRecord1 {
            get {
                return ResourceManager.GetString("SourceRecord1", resourceCulture);
            }
        }
    }
}
