select 'BAT:BE:'|| t.lot || ':' || t.facility || ':' || t.operation || ':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
    t.parameter_name ParameterName,
    DECODE(t.parameter_unit, '-', null,t.parameter_unit) ParameterUnit,
    t.sample_date SampleDate,
    t.sample_date_utc SampleDateUtc,
    t.ext_sample_size SampleSize,
    cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_Utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    DECODE(t.rv_store_flag, '-', null, t.rv_store_flag) RvStoreFlag,
    Decode(t.facility,'-',null, t.facility) Facility,
    Decode(t.operation,'-',null, t.operation) Operation,

    ----LDS specific 
    decode(t.package_type, '-', null, t.package_type) PackageType,
    decode(t."wiresize", '-',  null, t."wiresize") WireSize,
    decode(t.machine, '-', null, t.machine) ProcessEquipment,
    decode(t.machine, '-', null, t.machine) Machine,
    decode(t.package_class, '-', null, t.package_class) PackageClass,
    decode(t."classification", '-', null, t."classification") Classification,
    decode(t.die_set, '-', null, t.die_set) DieSet,
    decode(t.lot, '-', null, t.lot) Lot,
    decode(t."reserve1", '-', null, t."reserve1") Submission,
    decode(t."reserve2", '-', null, t."reserve2") Reserve2,
    decode(t."chiptype", '-', null, t."chiptype") ChipType,
    decode(t."reserve5", '-', null, t."reserve5") Area,
    decode(t.capillary, '-', null, t.capillary ) Capilary,
    decode(t.pad_metal, '-', null, t.pad_metal) PadMetal,
    decode(t.mc_platform, '-', null, t.mc_platform) McPlatform,
    decode(t.operator, '-', null, t.operator) Operator,
    decode(t.shift, '-', null, t.shift) Shift,
    decode(t.pc_id, '-', null, t.pc_id) OperatorId,
    decode(t.product, '-', null, t.product) Product,
    decode(t."reserve9", '-', null, t."reserve9") MeasurementEquipment,
    case when t.lds_id = 1010 then decode(t.package_abbreviation, '-', null, t.package_abbreviation)
        else decode(t.family_package, '-', null, t.family_package)
    END as PackageFamily,
    case when t.lds_id = 1010 then decode(t."packageid", '-', null, t."packageid")
        else decode(t.package, '-', null, t.package)
    END as Package,
    decode(t.process, '-', null, t.process) Process,
    decode(t.die_category, '-', null, t.die_category) DieCategory,
    decode(t.track, '-', null, t.track) Track,
    decode(t.lead_frame, '-', null, t.lead_frame) LeadFrame,
    decode(t.solder_glue, '-', null, t.solder_glue) SolderGlue,
    decode(t.tool, '-', null, t.tool) ProcessTool,
    decode(t.saw_street, '-', null, t.saw_street) SawStreet,
    decode(t.wafer_thickness, '-', null, t.wafer_thickness) WaferThickness,
    decode(t.blade_category, '-', null, t.blade_category) BladeCategory,
    decode(t."die_size", '-', null, t."die_size") DieSize,
    decode(t.gauge_id, '-', null, t.gauge_id) GaugeId,
    decode(t.cartidge_id, '-', null, t.cartidge_id) CartridgeID,
    decode(t.grade, '-', null, t.grade) Grade,
    decode(t.tester_id, '-', null, t.tester_id) SubmissionType,

    --Customer fields
    Decode(t."parameter_class", '-', null, t."parameter_class") ParameterClass,
    Decode(t."cf_comment", '-', null, t."cf_comment") CFComment,
    Decode(t."target_cpk", '-', null, t."target_cpk") TargetCpk,
    Decode(t."process_owner", '-', null, t."process_owner") ProcessOwner,
    Decode(t."segment", '-', null, t."segment") Segment,
    Decode(t.module, '-', null, t.module) Module,
    Decode(t."f56_parameter", '-', null, t."f56_parameter") F56Parameter,
    Decode(t."published", '-', null, t."published") Published,
    Decode(t."group_id", '-', null, t."group_id") GroupId,
    Decode(t.device, '-', null, t.device) Device,
    Decode(t."fourd_report", '-', null, t."fourd_report") FourDReport,
    Decode(t."special_characteristics", '-', null, t."special_characteristics") SpecialCharacteristics,

    --DATALAKE Properties
    t.lds_id LdsID,
    t."calc_created" CalcCreated,
    t."channel_type" ChannelType,
    t."ilds_id" ILdsID,
    t."spc_com_extern" SpcComExtern,
    t."spc_com_intern" SpcComIntern,
    t."accepct_flag" AcceptFlag,
    t."channel_state" ChState,
    t."updated_by" UpdatedBy,
    t."spec_target_origin" SpecTargetOrigin,
    t."viol_count" ViolCount,
    to_binary_double(t."ext_ma_mv") ExtMaMV,
    to_binary_double(t."ext_ewma_mv") ExtEwmaMV,
    to_binary_double(t."ext_ms_mv") ExtMsMV,
    t."out_of_order" OutOfOrder,
    t."ewma_s" EwmaS, 
    t."ewma_r" EwmaR,
    t."calc2_id" Calc2ID,
    t."limit_enable" LimitEnable,
    t."ext_ewma_mv_lcl" ExtEwmaMVLCL,
    t."ext_ewma_mv_center" ExtEwmaMVCenter,
    t."ext_ewma_mv_ucl" ExtEwmaMVUCL,
    t."ext_ma_mv_lcl" ExtMaMVLCL,
    t."ext_ma_mv_center" ExtMaMVCenter,
    t."ext_ma_mv_ucl" ExtMaMVUCL,
    t."ewma_s_lcl" EwmaSLCL, 
    t."ewma_s_center" EwmaSCenter, 
    t."ewma_s_ucl" EwmaSUCL,
    t."ewma_r_lcl" EwmaRLCL,
    t."ewma_r_center" EwmaRCenter,
    t."ewma_r_ucl" EwmaRUCL, 
    t."ext_ms_mv_lcl" ExtMSMVLCL,
    t."ext_ms_mv_center" ExtMSMVCenter, 
    t."ext_ms_mv_ucl" ExtMSMVUCL,
    t."cl_origin" ClOrigin,
    t."mv_lal" MVLal,
    t."mv_ual" MVUal,
    t."raw_lal" RawLal,
    t."raw_ual" RawUal,
    t."sigma_lal" SigmaLal,
    t."sigma_ual" SigmaUal,
    t."range_lal" RangeLal,
    t."range_ual" RangeUal,
    t."ext_spec_lower" ExtSpecLower,
    t."ext_spec_upper" ExtSpecUpper,
    t."ext_spec_lim_enable" ExtSpecLimEnable,
    t."CalculationStrategy" CalculationStrategy,
    --DATALAKE END
    t.ch_id ChannelId,
    t.ckc_id CkcId,
    t.ch_name ChannelName,
    t.ch_descr ChannelDescr,
    t.is_calc_param IsCalcParam, 
    'BE' SpaceInstanceName,
    'BAT' Sitekey,
    'Rawvalueslist' BreakPoint,
    t.sample_id SampleId,
    t.rv_seq_num Seqnr,
    t.raw_value Value,
    t.external_flagged ExternalFlagged,
    t.internal_flagged InternalFlagged,
    t.internal_comment InternalComment,
    t.num_violations NumViolations,
    t.violation_comments ViolationComments,
    t.violation_list ViolationList,
    t.primary_violation PrimaryViolation,
    t.primary_violation_comments PrimaryViolationComments 
from spaceods.v_pads_spc_bth t
where t.updated > :StartTime
 and t.updated <= :EndTime
 and t.lot <> '-'
 and t.lds_id in ('1010','1400')
order by t.lot,t.facility, t.operation,t.parameter_name, t.ch_id, t.sample_id,t.ckc_id 
