//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.TIJ.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.TIJ.PADS.Module.Tests.Properties.LotResources", typeof(LotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;PartNumber&quot;: &quot;MA005550128&quot;,
        ///        &quot;Track&quot;: &quot;A3477A&quot;,
        ///        &quot;Area&quot;: &quot;Plastic_Singulacion&quot;,
        ///        &quot;MeasLot&quot;: &quot;104OLWB.I01&quot;,
        ///        &quot;SiteKey&quot;: &quot;TIJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-10-10T03:35:37Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-10-09T20:35:37Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-10-10T03:35:37Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-10-09T20:35:37Z&quot;
        ///    },
        ///    &quot;Data_flat_Stra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;PartNumber&quot;: &quot;IRL40SC228&quot;,
        ///        &quot;Track&quot;: &quot;NA&quot;,
        ///        &quot;Area&quot;: &quot;Plastic_Singulacion&quot;,
        ///        &quot;MeasLot&quot;: &quot;104OMCQ.I01&quot;,
        ///        &quot;SiteKey&quot;: &quot;TIJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-10-10T02:51:24Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-10-09T19:51:24Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-10-10T02:51:24Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-10-09T19:51:24Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreFalse {
            get {
                return ResourceManager.GetString("PadsDocRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;PartNumber&quot;: &quot;IRL40SC228&quot;,
        ///        &quot;Track&quot;: &quot;NA&quot;,
        ///        &quot;Area&quot;: &quot;Plastic_Singulacion&quot;,
        ///        &quot;MeasLot&quot;: &quot;104OMCQ.I01&quot;,
        ///        &quot;SiteKey&quot;: &quot;TIJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-10-10T02:51:24Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-10-09T19:51:24Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-10-10T02:51:24Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-10-09T19:51:24Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreTrue {
            get {
                return ResourceManager.GetString("PadsDocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:TIJ:BE:104OLWB.I01:Plastic_Singulacion:Assy_EOL:BodyToGround_Distance:1048:3096890:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;PackageFamily&quot;: &quot;TO252&quot;,
        ///        &quot;Package&quot;: &quot;TO252-5&quot;,
        ///        &quot;Segment&quot;: &quot;Tijuana&quot;,
        ///        &quot;Module&quot;: &quot;Assy_EOL&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;SFMI461B&quot;,
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;Operator&quot;: &quot;MGOMEZ5&quot;,
        ///        &quot;PartNumber&quot;: &quot;MA005550128&quot;,
        ///        &quot;Track&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:TIJ:BE:104OMCQ.I01:Plastic_Singulacion:Assy_EOL:BodyToGround_Distance:1051:3096848:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;PackageFamily&quot;: &quot;TO263&quot;,
        ///        &quot;Package&quot;: &quot;TO263-7&quot;,
        ///        &quot;Segment&quot;: &quot;Tijuana&quot;,
        ///        &quot;Module&quot;: &quot;Assy_EOL&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;SGGE0550&quot;,
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;Operator&quot;: &quot;SALDANAR&quot;,
        ///        &quot;PartNumber&quot;: &quot;IRL40SC228&quot;,
        ///        &quot;Track&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreFalse {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:TIJ:BE:104OMCQ.I01:Plastic_Singulacion:Assy_EOL:BodyToGround_Distance:1051:3096848:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;PackageFamily&quot;: &quot;TO263&quot;,
        ///        &quot;Package&quot;: &quot;TO263-7&quot;,
        ///        &quot;Segment&quot;: &quot;Tijuana&quot;,
        ///        &quot;Module&quot;: &quot;Assy_EOL&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;SGGE0550&quot;,
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;Operator&quot;: &quot;SALDANAR&quot;,
        ///        &quot;PartNumber&quot;: &quot;IRL40SC228&quot;,
        ///        &quot;Track&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreTrue {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:TIJ:BE:104OMCQ.I01:Plastic_Singulacion:Assy_EOL:BodyToGround_Distance:1048:3096874:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;PackageFamily&quot;: &quot;TO252&quot;,
        ///        &quot;Package&quot;: &quot;TO252-5&quot;,
        ///        &quot;Segment&quot;: &quot;Tijuana&quot;,
        ///        &quot;Module&quot;: &quot;Assy_EOL&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;SFMI461B&quot;,
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;Operator&quot;: &quot;mgomez5&quot;,
        ///        &quot;PartNumber&quot;: &quot;MA005578209&quot;,
        ///        &quot;Track&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreFalse {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:TIJ:BE:104OMCQ.I01:Plastic_Singulacion:Assy_EOL:BodyToGround_Distance:1048:3096874:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;PackageFamily&quot;: &quot;TO252&quot;,
        ///        &quot;Package&quot;: &quot;TO252-5&quot;,
        ///        &quot;Segment&quot;: &quot;Tijuana&quot;,
        ///        &quot;Module&quot;: &quot;Assy_EOL&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;SFMI461B&quot;,
        ///        &quot;Classification&quot;: &quot;SPC-Monitoreo&quot;,
        ///        &quot;Operator&quot;: &quot;mgomez5&quot;,
        ///        &quot;PartNumber&quot;: &quot;MA005578209&quot;,
        ///        &quot;Track&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreTrue {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreTrue", resourceCulture);
            }
        }
    }
}
