//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.MKZ.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.MKZ.PADS.Module.Tests.Properties.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;IdSource&quot;:&quot;SPACEACT1:RBG:BE:3A140739:HFICR:-:bumpdiameter_All_bumps:49689:219254629:0&quot;,
        ///&quot;Data_flat_Metadata&quot;:
        ///{
        ///&quot;Segment&quot;:&quot;SCCM&quot;,
        ///&quot;GroupId&quot;:&quot;RBGEW273&quot;,
        ///&quot;Lot&quot;:&quot;3A140739&quot;,
        ///&quot;ParameterName&quot;:&quot;bumpdiameter_All_bumps&quot;,
        ///&quot;ParameterUnit&quot;:&quot;µm&quot;,
        ///&quot;ParameterFacility&quot;:&quot;HFICR&quot;,
        ///&quot;SiteKey&quot;:&quot;RBG&quot;,
        ///&quot;ChannelId&quot;:&quot;49689&quot;,
        ///&quot;SpaceInstanceName&quot;:&quot;BE&quot;,
        ///&quot;CreatedTimestampUtc&quot;:&quot;2021-08-05T22:58:25Z&quot;,
        ///&quot;CreatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestamp&quot;:&quot;2021-08-06T00:58:25Z&quot;,
        ///&quot;UpdatedTimestampUtc&quot;:&quot;2021-08-05T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
    }
}
