SELECT 'CEG:BE:'|| t.prodorder || ':' || t.line || ':'|| t.cf_comment ||':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
    t.parameter_name ParameterName,
    DECODE(t.parameter_unit, '-', null, t.parameter_unit) ParameterUnit,
    t.sample_date SampleDate,
    t.sample_date_utc SampleDateUtc,
    t.ext_sample_size SampleSize,
    cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_sigma_lcl) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.ext_range_lcl) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.spec_upper) as FLOAT(49)) SpecHigh,
    cast(to_number(t.spec_lower) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target) as FLOAT(49)) SpecTarget,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    t.rv_store_flag RvStoreFlag,
    t.ch_id ChannelId,
    t.ckc_id CkcId,
    t.ch_name ChannelName,
    t.ch_descr ChannelDescr,
    t.is_calc_param IsCalcParam, 
    'BE' SpaceInstanceName,
    'CEG' Sitekey,
    --DECODE START
    -- consistent in BE sites
    DECODE(t.parameter_class , '-', null, t.parameter_class) ParameterClass,
    DECODE(t.target_cpk , '-', null, t.target_cpk) TargetCpk,
    DECODE(t.segment , '-', null, t.segment) Segment,
    DECODE(t.f56_parameter , '-', null, t.f56_parameter) F56Parameter,
    DECODE(t.fourd_report , '-', null, t.fourd_report) FourDReport,
    DECODE(t.special_characteristics , '-', null, t.special_characteristics) SpecialCharacteristics,

    DECODE(t.plant , '-', null, t.plant) Plant,
    DECODE(t.qrkgroup, '-', null, t.qrkgroup)   QrkGroup,     
    DECODE(t.spcclass, '-', null, t.spcclass)   SpcClass,
    DECODE(t.paramtyp, '-', null, t.paramtyp)   ParameterType,
    DECODE(t.matnotxt, '-', null, t.matnotxt)   MaterialNumberText,
    DECODE(t.longparam, '-', null, t.longparam)   LongParameterName,
    DECODE(t.unit_length, '-', null, t.unit_length)   UnitLength,
    DECODE(t.operator, '-', null, t.operator)   Operator,

    DECODE(t.line , '-', null, t.line) Line,
    DECODE(t.prodorder , '-', null, t.prodorder) ProductionOrder,
    DECODE(t.batch, '-', null, t.batch) Batch,
    DECODE(t.matno, '-', null, t.matno) MaterialNumber,
    DECODE(t.prodgroup, '-', null, t.prodgroup) ProductGroup,
    DECODE(t.recipe, '-', null, t.recipe) MeasurementRecipe, 
    DECODE(t.ordertype, '-', null, t.ordertype)   OrderType,
    DECODE(t.process_owner , '-', null, t.process_owner) ProcessOwner,
    DECODE(t.group_id , '-', null, t.group_id) GroupId,
    DECODE(t.prozgroup, '-', null, t.prozgroup) ProcessGroup,
    DECODE(t.package , '-', null, t.package) Package,
    DECODE(t.module , '-', null, t.module) Module,

    DECODE(t.postname, '-', null, t.postname)   PosName,
    DECODE(t.ocapequipment, '-', null, t.ocapequipment)   OCAPEquipment,
    DECODE(t.cf_comment , '-', null, t.cf_comment) Operation,
    DECODE(t.published , '-', null, t.published) Published, 
    DECODE(t.nameprod, '-', null, t.nameprod) ProductName,
    DECODE(t.length, '-', null, t.length)  Length,
    DECODE(t.equipment , '-', null, t.equipment) ProcessEquipment,
    DECODE(t.nameeq , '-', null, t.nameeq) ProcessEquipmentName,
    DECODE(t.monEq, '-', null, t.monEq) MeasurementEquipment, 
    DECODE(t.namemoneq, '-', null, t.namemoneq) MeasurementEquipmentName,
    DECODE(t.extr1, '-', null, t.extr1) VariableExtr1,
    DECODE(t."Label_Extractorkey_Extr1", '-', null, t."Label_Extractorkey_Extr1") Label4Extr1,
    DECODE(t.extr2, '-', null, t.extr2) VariableExtr2,
    DECODE(t."Label_Extractorkey_Extr2", '-', null,  t."Label_Extractorkey_Extr2") Label4Extr2,
    DECODE(t.extr3, '-', null, t.extr3) VariableExtr3,
    DECODE(t."Label_Extractorkey_Extr3", '-', null,  t."Label_Extractorkey_Extr3") Label4Extr3,
    DECODE(t.extr4, '-', null, t.extr4) VariableExtr4,
    DECODE(t."Label_Extractorkey_Extr4", '-', null,  t."Label_Extractorkey_Extr4") Label4Extr4,
    DECODE(t.extr5, '-', null, t.extr5) VariableExtr5,
    DECODE(t."Label_Extractorkey_Extr5", '-', null,  t."Label_Extractorkey_Extr5") Label4Extr5,
    DECODE(t.extr6, '-', null, t.extr6) VariableExtr6,
    DECODE(t."Label_Extractorkey_Extr6", '-', null,  t."Label_Extractorkey_Extr6") Label4Extr6,
    --DECODE END
    CASE WHEN t.module LIKE '1%' THEN 'HPSModFAUF'
    WHEN t.module LIKE '0%' THEN 'HPSSubFAUF'
    ELSE 'ERROR'
    END IdSystemName,

    t.lds_id LdsID, -- Datalake attributes start from here ...
    t.calc_created CalcCreated,
    t.channel_type ChannelType,
    t.ilds_id ILdsID,
    t.spc_com_extern SpcComExtern,
    t.spc_com_intern SpcComIntern,
    t.accept_flag AcceptFlag,
    t."channel_state" ChState,
    t.updated_by UpdatedBy,
    t.spec_target_origin SpecTargetOrigin,
    t.viol_count ViolCount,
    to_binary_double(t.ext_ma_mv) ExtMaMV,
    to_binary_double(t.ext_ewma_mv) ExtEwmaMV,
    to_binary_double(t.ext_ms_mv) ExtMsMV,
    t.out_of_order OutOfOrder,
    t.ewma_s EwmaS,
    t.ewma_r EwmaR,
    t.calc2_id Calc2ID,
    t.limit_enable LimitEnable,
    t.ext_ewma_mv_lcl ExtEwmaMVLCL,
    t.ext_ewma_mv_center ExtEwmaMVCenter,
    t.ext_ewma_mv_ucl ExtEwmaMVUCL,
    t.ext_ma_mv_lcl ExtMaMVLCL,
    t.ext_ma_mv_center ExtMaMVCenter,
    t.ext_ma_mv_ucl ExtMaMVUCL,
    t.ewma_s_lcl EwmaSLCL,
    t.ewma_s_center EwmaSCenter,
    t.ewma_s_ucl EwmaSUCL,
    t.ewma_r_lcl EwmaRLCL,
    t.ewma_r_center EwmaRCenter,
    t.ewma_r_ucl EwmaRUCL, 
    t.ext_ms_mv_lcl ExtMSMVLCL,
    t.ext_ms_mv_center ExtMSMVCenter,
    t.ext_ms_mv_ucl ExtMSMVUCL,
    t.cl_origin ClOrigin,
    t.mv_lal MVLal,
    t.mv_ual MVUal,
    t.raw_lal RawLal,
    t.raw_ual RawUal,
    t.sigma_lal SigmaLal,
    t.sigma_ual SigmaUal,
    t.range_lal RangeLal,
    t.range_ual RangeUal,
    t.ext_spec_lower ExtSpecLower,
    t.ext_spec_upper ExtSpecUpper,
    t.ext_spec_lim_enable ExtSpecLimEnable,
    t."CalculationStrategy" CalculationStrategy,   
    'Rawvalueslist' BreakPoint,
    t.sample_id SampleId,
    t.rv_seq_num Seqnr,
    t.raw_value Value,
    t.external_flagged ExternalFlagged,
    t.internal_flagged InternalFlagged,
    t.internal_comment InternalComment,
    t.primary_violation PrimaryViolation,
    t.violation_list ViolationList,
    t.violation_comments ViolationComments,
    t.primary_violation_comments PrimaryViolationComments,
    t.num_violations NumViolations
FROM spaceods.v_pads_spc_ceg t
where t.updated > :StartTime
  and t.updated <= :EndTime
  and t.prodOrder not in ('88888888','11111111','22222222','33333333','44444444','55555555',
               '66666666','77777777','99999999','00112233','11223344','12345678','81628999')
  and regexp_like (t.prodOrder, '^[[:digit:]]{8}$')
  and t.line not in ('PELLET','DIFFUSION')
  AND LENGTH(COALESCE(TRIM(t.prodOrder),' ')) >4
  AND coalesce(TRIM(t.ckc_id),'0')='0'  
  AND SEGMENT='HPS'
order by 
    t.parameter_name,
    t.ch_id,
    t.sample_id,
    t.ckc_id
