//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.CJJ.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.CJJ.PADS.Module.Tests.Properties.LotResources", typeof(LotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;MeasLot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;
        ///    },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;MeasLot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;
        ///    },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreFalse {
            get {
                return ResourceManager.GetString("PadsDocRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;MeasLot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-12-10T13:22:28Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-12-10T22:22:28Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;
        ///    },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreTrue {
            get {
                return ResourceManager.GetString("PadsDocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:CJJ:BE:2Z34902B:::Lead_Length:59913:243031066:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Machine&quot;: &quot;LTF004&quot;,
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;ParameterClass&quot;: &quot;E_SPC&quot;,
        ///        &quot;Segment&quot;: &quot;IFPS&quot;,
        ///        &quot;Module&quot;: &quot;MiniFP&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;,
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;Lot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;ParameterName&quot;: &quot;Lead_Length&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;mm&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;ChannelId&quot;: &quot;5991 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:CJJ:BE:2Z34902B:::TipToTip_DistanceIn:59915:243031067:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Machine&quot;: &quot;LTF004&quot;,
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;ParameterClass&quot;: &quot;E_SPC&quot;,
        ///        &quot;Segment&quot;: &quot;IFPS&quot;,
        ///        &quot;Module&quot;: &quot;Tiny&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;,
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;Lot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;ParameterName&quot;: &quot;TipToTip_DistanceIn&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;mm&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreFalse {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:CJJ:BE:2Z34902B:::TipToTip_DistanceIn:59915:243031067:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Machine&quot;: &quot;LTF004&quot;,
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;ParameterClass&quot;: &quot;E_SPC&quot;,
        ///        &quot;Segment&quot;: &quot;IFPS&quot;,
        ///        &quot;Module&quot;: &quot;Tiny&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;,
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;Lot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;ParameterName&quot;: &quot;TipToTip_DistanceIn&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;mm&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreTrue {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:CJJ:BE:2Z34902B:::TipToTip_DistanceIn:59915:243031067:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Machine&quot;: &quot;LTF004&quot;,
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;ParameterClass&quot;: &quot;E_SPC&quot;,
        ///        &quot;Segment&quot;: &quot;IFPS&quot;,
        ///        &quot;Module&quot;: &quot;MiniFP&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;,
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;Lot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;ParameterName&quot;: &quot;TipToTip_DistanceIn&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;mm&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreFalse {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:CJJ:BE:2Z34902B:::TipToTip_DistanceIn:59915:243031067:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Machine&quot;: &quot;LTF004&quot;,
        ///        &quot;Operator&quot;: &quot;30156566&quot;,
        ///        &quot;Package&quot;: &quot;CIPOS MINI&quot;,
        ///        &quot;ParameterClass&quot;: &quot;E_SPC&quot;,
        ///        &quot;Segment&quot;: &quot;IFPS&quot;,
        ///        &quot;Module&quot;: &quot;MiniFP&quot;,
        ///        &quot;Device&quot;: &quot;IKCM15F60GA&quot;,
        ///        &quot;Shift&quot;: &quot;GY&quot;,
        ///        &quot;Lot&quot;: &quot;2Z34902B&quot;,
        ///        &quot;ParameterName&quot;: &quot;TipToTip_DistanceIn&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;mm&quot;,
        ///        &quot;SiteKey&quot;: &quot;CJJ&quot;,
        ///        &quot;C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreTrue {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreTrue", resourceCulture);
            }
        }
    }
}
