select 'WAR:BE:'|| t.production_order || ':' || t.line || ':'|| t."COMMENT" ||':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
       t.parameter_name ParameterName,
       DECODE(t.parameter_unit, '-', null,t.parameter_unit) ParameterUnit,
       t.sample_date SampleDate,
       t.sample_date_utc SampleDateUtc,
       t.ext_sample_size SampleSize,
       cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl ) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl ) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl ) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl ) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center ) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl ) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl ) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center ) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl ) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower ) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target ) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper ) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_Utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    DECODE(t.rv_store_flag, '-', null, t.rv_store_flag) RvStoreFlag,
    DECODE(t.plant, '-', null, t.plant) Plant,
    DECODE(t.line, '-', null, t.line) Line,
    DECODE(t.production_order, '-', null, t.production_order) ProductionOrder,
    DECODE(t.batch, '-', null, t.batch) Batch,
    DECODE(t.material_number, '-', null, t.material_number) MaterialNumber,
    DECODE(t.product_group, '-', null, t.product_group) ProductGroup,
    DECODE(t.variableextr1, '-', null, t.VariableExtr1) VariableExtr1,
    DECODE(t.label_for_extractorkey_extr1, '-', null, t.label_for_extractorkey_extr1) Label4Extr1,
    DECODE(t.variableextr2, '-', null, t.VariableExtr2) VariableExtr2,
    DECODE(t.label_for_extractorkey_extr2, '-', null,  t.label_for_extractorkey_extr2) Label4Extr2,
    DECODE(t.variableextr3, '-', null, t.VariableExtr3) VariableExtr3,
    DECODE(t.label_for_extractorkey_extr3, '-', null,  t.label_for_extractorkey_extr3) Label4Extr3,
    DECODE(t.variableextr4, '-', null, t.VariableExtr4) VariableExtr4,
    DECODE(t.label_for_extractorkey_extr4, '-', null,  t.label_for_extractorkey_extr4) Label4Extr4,
    DECODE(t.variableextr5, '-', null, t.VariableExtr5) VariableExtr5,
    DECODE(t.label_for_extractorkey_extr5, '-', null,  t.label_for_extractorkey_extr5) Label4Extr5,
    DECODE(t.variableextr6, '-', null, t.VariableExtr6) VariableExtr6,
    DECODE(t.label_for_extractorkey_extr6, '-', null,  t.label_for_extractorkey_extr6) Label4Extr6,
    DECODE(t.measurement_recipe, '-', null, t.measurement_recipe) MeasurementRecipe,
    DECODE(t.measurement_equipment, '-', null, t.measurement_equipment) MeasurementEquipment,
    DECODE(t.process_equipment, '-', null, t.process_equipment) ProcessEquipment,
    DECODE(t.order_type, '-', null, t.order_type)   OrderType,
    DECODE(t.qrk_group, '-', null, t.qrk_group)   QrkGroup,
    DECODE(t.process_group, '-', null, t.process_group) ProcessGroup,
    DECODE(t.spc_class, '-', null, t.spc_class)   SpcClass,
    DECODE(t.parameter_type, '-', null, t.parameter_type)   ParameterType,      
    DECODE(t.long_parameter_name, '-', null, t.long_parameter_name)   LongParameterName,
    DECODE(t.material_number_text, '-', null, t.material_number_text)   MaterialNumberText,
    DECODE(t.measurement_equipment_name, '-', null, t.measurement_equipment_name)   MeasurementEquipmentName,
    DECODE(t.process_equipment_name, '-', null, t.process_equipment_name)    ProcessEquipmentName,
    DECODE(t.product_name, '-', null, t.product_name)    ProductName,
    DECODE(t.raw_val_pos, '-', null, t.raw_val_pos)    RawValPos,
    DECODE(t.length_x, '-', null, t.length_x)   LengthX,
    DECODE(t.operator, '-', null, t.operator)   Operator,
    DECODE(t.status, '-', null, t.status)   Status,
    DECODE(t.unit_length, '-', null, t.unit_length)   UnitLength,
    DECODE(t."COMMENT",'-',null,t."COMMENT") Operation,
    DECODE(t.parameter_class, '-', null, t.parameter_class)  ParameterClass,
    DECODE(t.target_cpk, '-', null, t.target_cpk)   TargetCpk,
    DECODE(t.process_owner, '-', null, t.process_owner) ProcessOwner,
    DECODE(t.segment, '-', null, t.segment)   Segment,
    DECODE(t.package, '-', null, t.package)   Package,
    DECODE(t.f56_parameter, '-', null, t.f56_parameter) F56Parameter,
    DECODE(t.group_id, '-', null, t.group_id)   GroupId,
    DECODE(t.report, '-', null, t.report)   Report,
    DECODE(t.module, '-', null, t.module)   Module,
     CASE WHEN t.module LIKE '1%' THEN 'HPSModFAUF'
     WHEN t.module LIKE '0%' THEN 'HPSSubFAUF'
     ELSE 'ERROR'
     END IdSystemName,
       ch_id ChannelId,
       ckc_id CkcId,
       ch_name ChannelName,
       ch_descr ChannelDescr,
       'BE' SpaceInstanceName,
       'WAR' Sitekey,
       'Rawvalueslist' BreakPoint,
       t.sample_id SampleId,
        t.rv_seq_num Seqnr,
       t.raw_value Value,
       t.external_flagged ExternalFlagged,
       t.internal_flagged InternalFlagged,
       t.internal_comment InternalComment,
       t.num_violations NumViolations,
    t.violation_comments ViolationComments,
    t.violation_list ViolationList,
    t.primary_violation PrimaryViolation,
    t.primary_violation_comments PrimaryViolationComments
       from spaceods.v_pads_spc_war t
where t.updated > :StartTime
and t.updated <= :EndTime
and t.production_order not in ('88888888','11111111','22222222','33333333','44444444','55555555',
'66666666','77777777','99999999','00112233','11223344','12345678','81628999')
and regexp_like (t.production_order, '^[[:digit:]]{8}$')
and t.line not in ('PELLET','DIFFUSION')
AND LENGTH(COALESCE(TRIM(production_order),' ')) >4
AND coalesce(TRIM(ckc_id),'0')='0'  
AND SEGMENT='HPS'
order by t.production_order , t.line, t."COMMENT" , t.parameter_name , t.ch_id , t.sample_id , t.ckc_id
