//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.CEG.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.CEG.PADS.Module.Tests.Properties.LotResources", typeof(LotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///        &quot;SpcClass&quot;: &quot;2100&quot;,
        ///        &quot;CustomComment&quot;: &quot;system soldering&quot;,
        ///        &quot;Segment&quot;: &quot;HPS&quot;,
        ///        &quot;MeasLot&quot;: &quot;81771705&quot;,
        ///        &quot;ParameterOper&quot;: &quot;system so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///        &quot;SpcClass&quot;: &quot;2100&quot;,
        ///        &quot;CustomComment&quot;: &quot;system soldering&quot;,
        ///        &quot;Segment&quot;: &quot;HPS&quot;,
        ///        &quot;MeasLot&quot;: &quot;81771705&quot;,
        ///        &quot;ParameterOper&quot;: &quot;system so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreFalse {
            get {
                return ResourceManager.GetString("PadsDocRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///        &quot;SpcClass&quot;: &quot;2100&quot;,
        ///        &quot;CustomComment&quot;: &quot;system soldering&quot;,
        ///        &quot;Segment&quot;: &quot;HPS&quot;,
        ///        &quot;MeasLot&quot;: &quot;81771705&quot;,
        ///        &quot;ParameterOper&quot;: &quot;system so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreTrue {
            get {
                return ResourceManager.GetString("PadsDocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:CEG:BE:81771705:62mm:system soldering:K2-MFC:101002:332713726:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;0600&quot;,
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;10000973&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:CEG:BE:81771705:62mm:system soldering:K2-P-HCOOH:101003:332713719:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;0600&quot;,
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;10000973&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreFalse {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:CEG:BE:81771705:62mm:system soldering:K2-P-HCOOH:101003:332713719:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;0600&quot;,
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81771705&quot;,
        ///        &quot;Batch&quot;: &quot;UZ38277P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;42814&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62MM3.GEN&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;1&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;10000973&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreTrue {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:CEG:BE:81770078:62mm:system soldering:K2-t-HCOOH:101163:332712402:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;0600&quot;,
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81770078&quot;,
        ///        &quot;Batch&quot;: &quot;HF9651P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;50187&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62mmPACK&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;2&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;10001862&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreFalse {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT3:CEG:BE:81770078:62mm:system soldering:K2-t-HCOOH:101163:332712402:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Plant&quot;: &quot;0600&quot;,
        ///        &quot;Line&quot;: &quot;62mm&quot;,
        ///        &quot;ProductionOrder&quot;: &quot;81770078&quot;,
        ///        &quot;Batch&quot;: &quot;HF9651P0&quot;,
        ///        &quot;MaterialNumber&quot;: &quot;50187&quot;,
        ///        &quot;ProductGroup&quot;: &quot;M-62mmPACK&quot;,
        ///        &quot;MeasurementRecipe&quot;: &quot;2&quot;,
        ///        &quot;ProcessEquipment&quot;: &quot;10001862&quot;,
        ///        &quot;OrderType&quot;: &quot;2100&quot;,
        ///        &quot;QrkGroup&quot;: &quot;2100&quot;,
        ///        &quot;ProcessGroup&quot;: &quot;system_soldering&quot;,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreTrue {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreTrue", resourceCulture);
            }
        }
    }
}
