//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceNew.Source.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceNew.Source.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select t.parameter_name ||&apos;:&apos;|| t.ch_id ||&apos;:&apos; || t.sample_id || &apos;:&apos; || t.ckc_id  as &quot;PKey&quot;,
        ///    t.parameter_name &quot;ParameterName&quot;,
        ///    t.parameter_unit &quot;ParameterUnit&quot;,
        ///    t.sample_date &quot;SampleTimestamp&quot;,
        ///    t.sample_date_utc &quot;SampleTimestampUtc&quot;,
        ///    t.ext_sample_size &quot;SampleSize&quot;,
        ///    cast(t.ext_sigma as varchar(20)) &quot;Sigma&quot;,
        ///    cast(t.ext_mv as varchar(20)) &quot;Mean&quot;,
        ///    cast(t.ext_median as varchar(20)) &quot;Median&quot;,
        ///    cast(t.ext_min as varchar(20)) &quot;Min&quot;,
        ///    cast(t.ext_max as varchar(20)) &quot;Max&quot;,
        ///    cas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpaceSqlQuery {
            get {
                return ResourceManager.GetString("SpaceSqlQuery", resourceCulture);
            }
        }
    }
}
