SELECT 'CJJ:BE:'|| t.lot || ':' || t.facility || ':' || t.operation || ':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
    --GENERAL
    t.parameter_name ParameterName,
    DECODE(t.parameter_unit, '-', null,t.parameter_unit) ParameterUnit,
    t.sample_date SampleDate,
    t.sample_date_utc SampleDateUtc,
    t.ext_sample_size SampleSize,
    cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    t.created CreatedDate,
    t.created_Utc CreatedDateUtc,
    t.updated UpdatedDate,
    t.updated_utc UpdatedDateUtc,
    DECODE(t.rv_store_flag, '-', null, t.rv_store_flag) RvStoreFlag,
    Decode(t.facility,'-',null, t.facility) Facility,
    Decode(t.operation,'-',null, t.operation) Operation,
    
    ---LDS Specific 2305
    Decode(t.operation,'-',null, t.operation) SpecName,
    Decode(t.SalesName, '-',null,t.SalesName) SalesName,
    Decode(t.Equipment, '-',null,t.Equipment) MeasurementEquipment,
    Decode(t.Basictype, '-',null,t.Basictype) BasicType,
    Decode(t.Package, '-',null,t.Package) Package,
    Decode(t.PackageFamily, '-',null,t.PackageFamily) PackageFamily,
    Decode(t.DeviceFamily, '-',null,t.DeviceFamily) DeviceFamily,
    Decode(t.Owner, '-',null,t.Owner) Owner,
    Decode(t.PackageGroup, '-',null,t.PackageGroup) PackageGroup,
    Decode(t.PackageClass, '-',null,t.PackageClass) PackageClass,
    Decode(t.Baunumber, '-',null,t.Baunumber) Baunumber,
    Decode(t.BusinessSegment, '-',null,t.BusinessSegment) BusinessSegment,
    Decode(t.MoveInQuantity, '-',null,t.MoveInQuantity) MoveInQuantity,
    Decode(t.MoveOutQuantity, '-',null,t.MoveOutQuantity) MoveOutQuantity,
    Decode(t.OperatorId, '-',null,t.OperatorId) OperatorId,
    Decode(t.BeSegmentName, '-',null,t.BeSegmentName) BeSegmentName,
    Decode(t.ManufacturingWipLevel, '-',null,t.ManufacturingWipLevel) ManufacturingWipLevel,
    Decode(t.Device, '-',null,t.Device) Device,
    ---2300
    
    Decode(t.WireSize, '-',null,t.WireSize) WireSize,
    Decode(t.WireType, '-',null,t.WireType) WireType,
    Decode(t.Machine, '-',null,t.Machine) Machine,
    Decode(t.Process, '-',null,t.Process) Process,
    Decode(t.lot , '-', null, t.lot) Lot,
    Decode(t.ChipType, '-',null,t.ChipType) ChipType,
    Decode(t.Material, '-',null,t.Material) Material,
    Decode(t.Grade, '-',null,t.Grade) Grade,
    Decode(t.Shift, '-',null,t.Shift) Shift,
    Decode(t.Operator, '-',null,t.Operator) Operator,
    Decode(t.Classification, '-',null,t.Classification) Classification,
    Decode(t.CartridgeID, '-',null,t.CartridgeID) CartridgeID,
    Decode(t.MaterialType, '-',null,t.MaterialType) MaterialType,
    
    ---2400
    Decode(t.ChipType, '-',null,t.ChipType) ChipType,
    Decode(t.WaferThickness, '-',null,t.WaferThickness) WaferThickness,
    
    --Customer fields
    Decode(t."parameter_class", '-', null, t."parameter_class") ParameterClass,
    Decode(t."cf_comment", '-', null, t."cf_comment") CFComment,
    Decode(t."target_cpk", '-', null, t."target_cpk") TargetCpk,
    Decode(t."process_owner", '-', null, t."process_owner") ProcessOwner,
    Decode(t."segment", '-', null, t."segment") Segment,
    Decode(t."module", '-', null, t."module") Module,
    Decode(t."f56_parameter", '-', null, t."f56_parameter") F56Parameter,
    Decode(t."published", '-', null, t."published") Published,
    Decode(t."group_id", '-', null, t."group_id") GroupId,
    Decode(t."fourd_report", '-', null, t."fourd_report") FourDReport,
    Decode(t."special_characteristics", '-', null, t."special_characteristics") SpecialCharacteristics,
    
     --DATALAKE Properties
    t.lds_id LdsID,
    t.calc_created CalcCreated,
    t.channel_type ChannelType,
    t.ilds_id ILdsID,
    t.spc_com_extern SpcComExtern,
    t.spc_com_intern SpcComIntern,
    t.accept_flag AcceptFlag,
    t.channel_state ChState,
    t.updated_by UpdatedBy,
    t.spec_target_origin SpecTargetOrigin,
    t.viol_count ViolCount,
    to_binary_double(t.ext_ma_mv) ExtMaMV,
    to_binary_double(t.ext_ewma_mv) ExtEwmaMV,
    to_binary_double(t.ext_ms_mv) ExtMsMV,
    t.out_of_order OutOfOrder,
    t.ewma_s EwmaS, 
    t.ewma_r EwmaR,
    t.calc2_id Calc2ID,
    t.limit_enable LimitEnable,
    t.ext_ewma_mv_lcl ExtEwmaMVLCL,
    t.ext_ewma_mv_center ExtEwmaMVCenter,
    t.ext_ewma_mv_ucl ExtEwmaMVUCL,
    t.ext_ma_mv_lcl ExtMaMVLCL,
    t.ext_ma_mv_center ExtMaMVCenter,
    t.ext_ma_mv_ucl ExtMaMVUCL,
    t.ewma_s_lcl EwmaSLCL, 
    t.ewma_s_center EwmaSCenter, 
    t.ewma_s_ucl EwmaSUCL,
    t.ewma_r_lcl EwmaRLCL,
    t.ewma_r_center EwmaRCenter,
    t.ewma_r_ucl EwmaRUCL, 
    t.ext_ms_mv_lcl ExtMSMVLCL,
    t.ext_ms_mv_center ExtMSMVCenter, 
    t.ext_ms_mv_ucl ExtMSMVUCL,
    t.cl_origin ClOrigin,
    t.mv_lal MVLal,
    t.mv_ual MVUal,
    t.raw_lal RawLal,
    t.raw_ual RawUal,
    t.sigma_lal SigmaLal,
    t.sigma_ual SigmaUal,
    t.range_lal RangeLal,
    t.range_ual RangeUal,
    t.ext_spec_lower ExtSpecLower,
    t.ext_spec_upper ExtSpecUpper,
    t.ext_spec_lim_enable ExtSpecLimEnable,
    t."CalculationStrategy" CalculationStrategy,
    --DATALAKE END
    t.ch_id ChannelId,
    t.ckc_id CkcId,
    t.ch_name ChannelName,
    t.ch_descr ChannelDescr,
    t."is_calc_param" IsCalcParam, 
    'BE' SpaceInstanceName,
    'CJJ' Sitekey,
    'Rawvalueslist' BreakPoint,
    t.sample_id SampleId,
    t.rv_seq_num Seqnr,
    t.raw_value Value,
    t.external_flagged ExternalFlagged,
    t.internal_flagged InternalFlagged,
    t.internal_comment InternalComment,
    t.num_violations NumViolations,
    t.violation_comments ViolationComments,
    t.violation_list ViolationList,
    t.primary_violation PrimaryViolation,
    t.primary_violation_comments PrimaryViolationComments 
FROM spaceods.v_pads_spc_cjj t
where t.updated > :StartTime
 and t.updated <= :EndTime
 and t.lot <> '-'
order by t.lot,t.facility, t.operation,t.parameter_name, t.ch_id, t.sample_id,t.ckc_id 
