//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDS.SpaceBE.WUX.PADS.Module.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDS.SpaceBE.WUX.PADS.Module.Tests.Properties.LotResources", typeof(LotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-11-14T08:20:40Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-11-14T15:20:40Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-11-14T08:20:40Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-11-14T15:20:40Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDoc {
            get {
                return ResourceManager.GetString("PadsDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-11-14T08:21:10Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-11-14T15:21:10Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-11-14T08:21:10Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-11-14T15:21:10Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreFalse {
            get {
                return ResourceManager.GetString("PadsDocRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;SpaceInstanceName&quot;: &quot;BE&quot;,
        ///        &quot;BeginTimestampUtc&quot;: &quot;2023-11-14T08:21:10Z&quot;,
        ///        &quot;BeginTimestamp&quot;: &quot;2023-11-14T15:21:10Z&quot;,
        ///        &quot;EndTimestampUtc&quot;: &quot;2023-11-14T08:21:10Z&quot;,
        ///        &quot;EndTimestamp&quot;: &quot;2023-11-14T15:21:10Z&quot;
        ///    },
        ///    &quot;Data_flat_StrangeMetadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PadsDocRvStoreTrue {
            get {
                return ResourceManager.GetString("PadsDocRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:WUX:BE:PF345816B01:BE1I:A2_Plating:WedgeBumpPullTest:70967:240193046:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;CFComment&quot;: &quot;FOL&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        ///        &quot;F56Parameter&quot;: &quot;N&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterName&quot;: &quot;WedgeBumpPullTest&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;g&quot;,
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;ChannelId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNew {
            get {
                return ResourceManager.GetString("TestCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:WUX:BE:PF345816B01:BE1I:A2_Plating:WedgeBumpPullTest:71452:240193049:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;CFComment&quot;: &quot;FOL&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        ///        &quot;F56Parameter&quot;: &quot;N&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterName&quot;: &quot;WedgeBumpPullTest&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;g&quot;,
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;ChannelId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreFalse {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:WUX:BE:PF345816B01:BE1I:A2_Plating:WedgeBumpPullTest:71452:240193049:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;CFComment&quot;: &quot;FOL&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        ///        &quot;F56Parameter&quot;: &quot;N&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterName&quot;: &quot;WedgeBumpPullTest&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;g&quot;,
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;ChannelId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCreateNewRvStoreTrue {
            get {
                return ResourceManager.GetString("TestCreateNewRvStoreTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:WUX:BE:PF345816B01:BE1I:A2_Plating:WirePull:11432:240193044:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;CFComment&quot;: &quot;FOL&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        ///        &quot;F56Parameter&quot;: &quot;N&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterName&quot;: &quot;WirePull&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;g&quot;,
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;ChannelId&quot;: &quot;11432&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreFalse {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;IdSource&quot;: &quot;SPACEACT2:WUX:BE:PF345816B01:BE1I:A2_Plating:WirePull:11432:240193044:0&quot;,
        ///    &quot;Data_flat_Metadata&quot;: {
        ///        &quot;Device&quot;: &quot;U0163B&quot;,
        ///        &quot;ParameterClass&quot;: &quot;PPAP&quot;,
        ///        &quot;CFComment&quot;: &quot;FOL&quot;,
        ///        &quot;Segment&quot;: &quot;WB&quot;,
        ///        &quot;F56Parameter&quot;: &quot;N&quot;,
        ///        &quot;FourDReport&quot;: &quot;*&quot;,
        ///        &quot;ParameterName&quot;: &quot;WirePull&quot;,
        ///        &quot;ParameterUnit&quot;: &quot;g&quot;,
        ///        &quot;ParameterOper&quot;: &quot;A2_Plating&quot;,
        ///        &quot;ParameterFacility&quot;: &quot;BE1I&quot;,
        ///        &quot;SiteKey&quot;: &quot;WUX&quot;,
        ///        &quot;ChannelId&quot;: &quot;11432&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestUpdateNewParamRvStoreTrue {
            get {
                return ResourceManager.GetString("TestUpdateNewParamRvStoreTrue", resourceCulture);
            }
        }
    }
}
