select 'RBG:FE'|| ':' || t.lot || ':' || t.facility || ':' || t.operation || ':' || t.parameter_name || ':' || t.ch_id ||':' || t.sample_id || ':' || t.ckc_id as PKey,
    t.parameter_name ParameterName,
    DECODE(t.parameter_unit, '-', null, t.parameter_unit) ParameterUnit,
    t.ext_sample_size SampleSize,
    cast(t.ext_sigma as varchar(20)) Sigma,
    cast(t.ext_mv as varchar(20)) Mean,
    cast(t.ext_median as varchar(20)) Median,
    cast(t.ext_min as varchar(20)) Min,
    cast(t.ext_max as varchar(20)) Max,
    cast(t.ext_q1 as varchar(20)) Q1,
    cast(t.ext_q3 as varchar(20)) Q3,
    cast(to_number(t.ext_mv_lcl) as FLOAT(49)) MeanCntrlLow,
    cast(to_number(t.ext_mv_center) as FLOAT(49)) MeanCntrlTarget,
    cast(to_number(t.ext_mv_ucl ) as FLOAT(49)) MeanCntrlHigh,
    cast(to_number(t.ext_raw_lcl ) as FLOAT(49)) CntrlLow,
    cast(to_number(t.ext_raw_center) as FLOAT(49)) CntrlTarget,
    cast(to_number(t.ext_raw_ucl ) as FLOAT(49)) CntrlHigh,
    cast(to_number(t.ext_range_lcl ) as FLOAT(49)) RangeCntrlLow,
    cast(to_number(t.ext_range_center ) as FLOAT(49)) RangeCntrlTarget,
    cast(to_number(t.ext_range_ucl ) as FLOAT(49)) RangeCntrlHigh,
    cast(to_number(t.ext_sigma_lcl ) as FLOAT(49)) SigmaCntrlLow,
    cast(to_number(t.ext_sigma_center ) as FLOAT(49)) SigmaCntrlTarget,
    cast(to_number(t.ext_sigma_ucl ) as FLOAT(49)) SigmaCntrlHigh,
    cast(to_number(t.spec_lower ) as FLOAT(49)) SpecLow,
    cast(to_number(t.spec_target ) as FLOAT(49)) SpecTarget,
    cast(to_number(t.spec_upper ) as FLOAT(49)) SpecHigh,
    t.mv_ucl_enabled CtrlMeanHighEnabled,
    t.mv_lcl_enabled CtrlMeanLowEnabled,    
    t.mv_center_enabled CtrlMeanTargetEnabled,
    t.raw_lcl_enabled CtrlLowEnabled,
    t.raw_center_enabled CtrlCenterEnabled,
    t.raw_ucl_enabled CtrlHighEnabled,
    t.range_lcl_enabled CtrlRangeLowEnabled,
    t.range_center_enabled CtrlRangeCenterEnabled,
    t.range_ucl_enabled CtrlRangeHighEnabled,
    t.sigma_lcl_enabled CtrlSigmaLowEnabled,
    t.sigma_center_enabled CtrlSigmaCenterEnabled,
    t.sigma_ucl_enabled CtrlSigmaHighEnabled,
    t.spec_lower_enabled SpecLowEnabled,
    t.spec_upper_enabled SpecHighEnabled,
    DECODE(t.rv_store_flag, '-', null, t.rv_store_flag) RvStoreFlag,
    DECODE(t.epa, '-', null, t.epa) SPSNumber,
    DECODE(t.pg3, '-', null, t.pg3) ProcessGroup,
    DECODE(t.product_type, '-', null, t.product_type) ProductType,
    DECODE(t.product, '-', null, t.product) Product,
    DECODE(t.basictype, '-', null, t.basictype) BasicType,
    DECODE(t.route, '-', null, t.route) Route,
    DECODE(t.measurement_recipe, '-', null, t.measurement_recipe) Recipe,
    DECODE(t.processline, '-', null, t.processline) ProcessLine,
    DECODE(t.process_equipment, '-', null, t.process_equipment) ProcessEquipment,
    DECODE(t.measurement_equipment_Type, '-', null, t.measurement_equipment_type) MeasurementEquipmentType,
    DECODE(t.operation, '-', null, t.operation) Operation,
    DECODE(t.design, '-', null, t.design) Design,
    DECODE(t.facility, '-', null, t.facility) Facility,
    DECODE(t.layer, '-', null, t.layer) Layer,
    DECODE(t.measurement_equipment, '-', null, t.measurement_equipment) MeasurementEquipment,
    DECODE(t.measurement_batch, '-', null, t.measurement_batch) MeasurementBatch,
    t.lot Lot,
    DECODE(t.process_batch, '-', null, t.process_batch) ProcessBatch,
    t.ch_id ChannelId,
    t.ckc_id CkcId,
    t.ch_name ChannelName,
    t.ch_descr ChannelDescr,
    'FE' SpaceInstanceName,
    'RBG' Sitekey,
    DECODE(t.wafername, '-', null, t.wafername) MotherlotWafer,
    cast(t.created as timestamp) as CreatedDate,
    cast((from_tz(cast(t.created as timestamp), 'Europe/Berlin') at time zone 'UTC') as timestamp) as CreatedDateUtc,     
    cast(t.updated as timestamp) as UpdatedDate,    
    cast((from_tz(cast(t.updated as timestamp), 'Europe/Berlin') at time zone 'UTC') as timestamp) as UpdatedDateUtc,     
    cast(t.sample_date as timestamp) as SampleDate,
    cast((from_tz(cast(t.sample_date as timestamp), 'Europe/Berlin') at time zone 'UTC') as timestamp) as SampleDateUtc,
    'Rawvalueslist' BreakPoint,
    DECODE(t.x, '-', null, t.x) X,
    DECODE(t.y, '-', null, t.y) Y,
    DECODE(t.GOF, '-', null, t.GOF) GOF,
    DECODE(t.process_equipment, '-', null, t.process_equipment) ProcessEquipment,
    DECODE(t.slot_position, '-', null, t.slot_position) Slot,
    Decode(t.testpos, '-', null, '.', null, t.testpos) TestPosition,
    DECODE(t.wafername, '-', null, t.wafername) WaferName,
    DECODE(t.wafer_sequence, '-', null, t.wafer_sequence)  WaferSequence,
    t.rv_seq_num Seqnr,
    cast(t.raw_value as FLOAT(49)) Value,
    t.sample_id SampleId,
    t.external_flagged ExternalFlagged,
    t.internal_flagged InternalFlagged,
    t.internal_comment InternalComment,
    t.num_violations NumViolations,
    t.violation_comments ViolationComments,
    t.violation_list ViolationList,
    t.primary_violation PrimaryViolation,
    t.primary_violation_comments PrimaryViolationComments    
from spaceods.v_pads_spc_rbg_fe t
where
t.updated > :StartTime
and t.updated <= :EndTime and
t.parameter_name not in ('GOF', 'Luftdruck')
and t.ext_sample_size < 1800
order by t.lot,t.facility , t.operation ,t.parameter_name , t.ch_id, t.sample_id ,t.ckc_id
